### ISSUE TITLE
Monitoring of "podMonitor" and  "serviceMonitor" from team namespaces not working if multitenant disabled mode

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#1000]
Hi there,

I noticed that our Prometheus XXNamespaceSelectors in our templates does not contain logic allowing the global instance of Prometheus to target team namespaces even if multitenancy is disabled.

Prometheus-operator.gotmpl:
```

prometheus:
  enabled: {{ $p.enabled }}
  prometheusSpec:
    {{- range $selType := list "podMonitor" "probe" "rule" "serviceMonitor" }}
    {{ $selType }}NamespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            {{- range $teamId, $_ := $v.teamConfig }}
            - team-{{ $teamId }}
            {{- end }}

```

Suggested fix is to extend this logic to allow the global instance to target team namespaces if multitenancy is disabled

Cheers

**Comment by Morriz** [comment]
> Hi there,
> 
> 
> 
> I noticed that our Prometheus XXNamespaceSelectors in our templates does not contain logic allowing the global instance of Prometheus to target team namespaces even if multitenancy is disabled.
> 

Thanks. Just some facts about current state of things (which can be improved upon for sure):

1. Only when multitenancy is enabled do we deploy team prometheuses.
2. Team prometheuses are not governing what platform prometheus is already governing, and are not given any rulesets therefor. In effect this allows teams to publish custom metrics which team prometheuses act on. Nothing else (yet).

**Comment by Morriz** [comment]
So I believe your initial observation about global prom not governing team namespaces is incorrect as it is not namespaced.

**Comment by staticvoid255** [comment]
Hi there,

I have updated the title for clarity.
Can you please point to me in code where the NotIn team namespace constraint is lifted in the event that multitenancy is disabled, as from what I can see this constraint is `always ` applied regardless of disabled or not.

**Comment by staticvoid255** [comment]
Drone pipeline logs - multitenancy disabled:
<img width="339" alt="Screenshot 2023-01-11 at 20 05 58" src="https://user-images.githubusercontent.com/59235486/211895830-b0b713d4-01c7-4d6f-aa52-5fc9a55c6b0d.png">

@Morriz please advise

**Comment by Morriz** [comment]
If that is the case then that is clearly not the way it should be.
