### ISSUE TITLE
Use custom IP address for external-dns

### ISSUE THREAD

**Issue by srodenhuis** [redkubes/otomi-core#1004]
As an admin I would like to use DNS with a custom IP address instead of the load balancer IP.
This is required for scenarios where Otomi runs behind a firewall, and uses a private load balancer IP. The DNS A records should have the IP of the front-facing FW, while traffic is forwarded the private IP of the load balancer using SNAT.

**Comment by Morriz** [comment]
But this is already possible just through configuration of ingress-nginx @srodenhuis.

**Comment by Morriz** [comment]
As discussed set the ip on `$v.cluster.entrypoint` and make sure that there is a route from that ip to the loadbalancer ip
