### ISSUE TITLE
Installation of Otomi has failed

### ISSUE THREAD

**Issue by alextermanPL** [redkubes/otomi-core#1023]
**The Otomi installation job has failed** 
I am discovering the Otomi platform and trying to run it locally using the Minikube cluster on my MacBook.
I am following the steps from https://otomi.io/docs/get-started/installation

**To Reproduce**

1. Go to 'https://otomi.io/docs/get-started/installation' and follow the installation instructions.
2. After running the installation command `helm install -f values.yaml otomi otomi/otomi` I am using `kubectl get job otomi -w` to monitor the job status

4. The job is never complete
<img width="513" alt="Screenshot 2023-01-27 at 14 47 49" src="https://user-images.githubusercontent.com/122780730/215102078-8b38d5e5-4a10-4ecc-866a-46fb7dfe8aef.png">

The `ingress-nginx-platform` seems not started

6. I see nginx related errors in log `kubectl logs jobs/otomi -n default -f` 
<img width="1440" alt="Screenshot 2023-01-27 at 14 40 27" src="https://user-images.githubusercontent.com/122780730/215102859-214686a3-8d43-4889-b1d9-f6250606e930.png">

**Expected behavior:** 
The installation job is to be completed and start all the containers

**Screenshots:** (if applicable, add screenshots to help explain your problem)
<img width="1087" alt="Screenshot 2023-01-27 at 14 55 11" src="https://user-images.githubusercontent.com/122780730/215103735-eaa21fcd-01a8-4df6-be0f-762fec3841aa.png">

**Cluster(s):**
minikube version: v1.28.0
kubernetes-version v1.22.17 (tried also the default one, that shipped with minikube)

**Versions:**
APP VERSION: v0.18.0
CHART: otomi-0.5.28

**Desktop:**
- OS: [MacOs]
- Version [13.1 ]

**Comment by srodenhuis** [comment]
Hi Alex,

What driver are you using? Otomi requires an external load balancer IP and can not be installed with the default docker driver. It looks like the nginx svc is not able to get an external IP. So you'll need to use the hyperkit driver (on intel architecture):

```
minikube start --driver=hyperkit --kubernetes-version=v1.22.4 --cni calico
```
and then install Metallb:

```
minikube addons enable metallb
```

You can find more detailed instructions in this blog post: https://itnext.io/installing-otomi-on-minikube-2f83dfc421d2
or check the quickstart project: https://github.com/redkubes/quickstart/tree/main/minikube

Also, be aware that enabling more apps in Otomi requires more resources ;-)

**Comment by alextermanPL** [comment]
Hi @srodenhuis,

Thank you for the detailed answer.
I will go through the resources you shared.
