### ISSUE TITLE
Activation steps link in the Github repo readme is broken

### ISSUE THREAD

**Issue by arunans23** [redkubes/otomi-core#1039]
**Describe the bug:** (a clear and concise description of what the bug is)

The activation steps link in the Github repo readme is broken. 

```
[activation steps](https://otomi.io/docs/installation/activation/).
```

Correct link should be https://otomi.io/docs/get-started/activation/

**Comment by srodenhuis** [comment]
Thanks for pointing that out. We recently did some updates on the docs in otomi.io. You can find the activation steps here: https://otomi.io/docs/get-started/activation

**Comment by srodenhuis** [comment]
fixed!
