### ISSUE TITLE
network timeout at: https://keycloak.xx.xx.xx.xx.nip.io/

### ISSUE THREAD

**Issue by iamavi9** [redkubes/otomi-core#1072]
**Network timeout at release=wait-for-otomi-realm**

**To Reproduce**
Running the helm install command on GKE cluster with version 1.23.16-gke.1400

**Expected behavior:** Otomi job log should show - "To start using Otomi, go to https://<your-ip>.nip.io and sign in to the web console  with username "otomi-admin" and password "password".

**Screenshots:** 
![image](https://user-images.githubusercontent.com/68109125/230914557-ecb82a24-e191-49c8-9344-5212e99d87fa.png)
![image](https://user-images.githubusercontent.com/68109125/230914859-536d305e-ee5f-4c45-af1e-9829599610a0.png)

- Cloud: Google

**Versions:** 1.23.16-gke-.1400

**Comment by srodenhuis** [comment]
The wait-for-otomi-realm is a job that checks to see if keycloak is active. If this check fails, the installer will stop. Please first check to see if keycloak is installed and in a ready state.

**Comment by iamavi9** [comment]
Keycloak is in ready state and no error in pod logs. Below is the screenshot.
![image](https://user-images.githubusercontent.com/68109125/231157416-e6388d85-e953-4b0c-90e6-f271b2d2316f.png)

**Comment by iamavi9** [comment]
Yes, I can see external IP for that service. Will try to uninstall and install again.
![image](https://user-images.githubusercontent.com/68109125/231183015-68a1217f-8d65-4605-94e9-4f80a4734918.png)

**Comment by iamavi9** [comment]
I am able to now access Otomi console. The issue is with my MetalLB configuration not allocating externalIP to nginx ingress. Thank you for your support @srodenhuis closing this issue now.

**Comment by RubenvdKamp08** [comment]
@iamavi9 / @srodenhuis how did you eventually solve the issue with the MetalLB configuration not allocating externalIP to nginx ingress. Currently having the same issue, but no solution on how to solve this.

**Comment by srodenhuis** [comment]
Hi @RubenvdKamp08 Metallb needs to be configured with an external IP upfront and this IP needs to be accessible from within the cluster. Maybe the minikube quickstart provides some more information on how to install Otomi on Minikube: https://github.com/redkubes/quickstart/tree/main/minikube

**Comment by RubenvdKamp08** [comment]
Yes, I followed all the steps, and validated if keycloak is running and if the ngnix has an external IP (same as above), but it keeps failing at the `wait-for-otomi-realm`. Using an intel mac. Thanks in advance for helping @srodenhuis

**Comment by srodenhuis** [comment]
I don't think the minikube version matters as long as you are using k8s version 1.23 or 1.24. As of Otomi version 0.21.0, k8s version 1.21 and 1.22 are no longer supported. But not sure if this matters. The wait-for jobs will try to access keycloak using the external IP and will fail if it can not.
