### ISSUE TITLE
invalid_request after logging in to access drone

### ISSUE THREAD

**Issue by CasLubbers** [redkubes/otomi-core#1101]
**Describe the bug:**
I cannot access drone after a fresh Otomi install. The login for gitea works but I get the error 'invalid_request' when trying to access Drone, se example video.

**To Reproduce**
Steps to reproduce the behaviour:

1. Login to Otomi (I used default admin user)
2. Click on Apps -> Drone
3. Login to Drone

**Expected behaviour:**
Acces to drone after successfully logging in.
**Screenshots:** (if applicable, add screenshots to help explain your problem)
https://images.zenhubusercontent.com/200118806/0b8fec3b-fc50-411b-9bc9-59309171b23a/screen_recording_2023_05_01_at_15_43_53.mov
![Screenshot 2023-05-01 at 16.00.56.png](https://images.zenhubusercontent.com/644f9e16db9d221173275566/46d78c24-47b0-4256-b7e4-bdfccf9252a9)
**Versions:**

- Kubernetes: 1.25
- Otomi Core main
- Otomi API main
- Otomi Console main

I executed github action workflow 'Deploy Otomi' from main [(f1ce10b)](https://github.com/redkubes/otomi-core/commit/f1ce10b3c02598906a38c2d85f835acd678531d8)  with kubernetes version 1.25.

**Comment by CasLubbers** [comment]
Got the same issue using Kubernetes 1.24 with latest main [(f1ce10b)](https://github.com/redkubes/otomi-core/commit/f1ce10b3c02598906a38c2d85f835acd678531d8)

**Comment by Ani1357** [comment]
created [PR](https://github.com/redkubes/otomi-tasks/pull/79)
