### ISSUE TITLE
Migrate keycloak database to postgres cluster spawn by cloudNativePG

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1122]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by staticvoid255** [comment]
Hi Jeho,

Needs a bit more detail - unclear on what to do here.

**Comment by staticvoid255** [comment]
still waiting for information

**Comment by j-zimnowoda** [comment]
Opened PR to load this info
