### ISSUE TITLE
Upgrade ingress-nginx chart

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1124]
**Is your feature request related to a problem? Please describe.** 

From:
```
1.1.2      
4.0.18     
```
to:

```
appVersion: 1.7.1
version: 4.6.1
```

See: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Ani1357** [comment]
Upgraded ingress-nginx chart to version 4.6.1 which uses nginx ingress version 1.7.1.
Tested upgrade path from v0.21.6 and v0.22.0 without any issues. 
Created PR[#1176](https://github.com/redkubes/otomi-core/pull/1176)
