### ISSUE TITLE
Upgrade kube-prometheus-stack chart

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1125]
**Is your feature request related to a problem? Please describe.** 

From:
```
appVersion: 0.57.0     
version: 36.2.0     
```
To:
```
appVersion: 0.65.1
version: 46.4.0
```
See: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by srodenhuis** [comment]
Will upgrade to:
appVersion 0.65.1
chart version 46.4.1
