### ISSUE TITLE
Add Cilium Install to Integrated K8s Applications

### ISSUE THREAD

**Issue by seifrajhi** [redkubes/otomi-core#1146]
**Is your feature request related to a problem? Please describe.**

Currently, when using Integrated K8s Applications in Otomi, I am unable to install `Cilium` eBPF based, which limits my ability to implement specific networking features.

**Describe the solution you'd like**
I would like to have the ability to install Cilium as part of the Integrated K8s Applications in Otomi. This would enable me to take advantage of Cilium's advanced networking capabilities and improve the overall security and performance of my applications

**Describe alternatives you've considered**
As an alternative, I have looked into manually installing Cilium after deploying the Integrated K8s Applications, but this approach is cumbersome and adds additional complexity to the deployment process.

**Additional context**
Add any other relevant information, context, or screenshots about the feature request here. This could include specific use cases, examples, or any other details that can help the project maintainers understand the importance and impact of this feature request.

Otomi already install Istio and Calico as CNI

**Comment by j-zimnowoda** [comment]
We decided to not include any CNI as a part of Otomi app suite because CNI is infrastructure specific design choice and should be  part of k8s cluster installation.
