### ISSUE TITLE
decouple Keycloak DB from  databases from the community chart

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1195]
# Description

# Acceptance criteria

AS A
I WANT TO
SO

# Acceptance criteria

GIVEN
WHEN
THEN

# Definition of done

- [ ] Relevant PRs are merged
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer

**Comment by staticvoid255** [comment]
Please also test this feature in the context of backup and restore with Velero
