### ISSUE TITLE
Print HTTP 400 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1220]
# WHY
Self service for error handling.

# User Story

**AS A** user 

**I WANT TO** see HTTP error content in addition to HTTP 400 message

**SO** so I have better understanding of what is wrong

# Acceptance criteria

**GIVEN** data in my values repo does not confirm to the OpenApi spec (was edited manually)

**WHEN** I edit the resource via Otomi console

**THEN** I get HTTP 400 together with the message.

# Definition of done

- [x] Relevant PRs are merged
- [x] Tested by peer
- [x] Updated documentation reviewed by peer
- [x] Short demo video recorded and stored on google drive (if applicable)

**Comment by ferruhcihan** [comment]
Uploaded a demo video:
https://drive.google.com/file/d/10NvGG0qWVSQKhtZi-k7o6qe5ZIpV0I9Y/view?usp=drive_link
