### ISSUE TITLE
Otomi SHELL termination

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1237]
# WHY

To save resources by deleting TTY pods that are not used.
To ensure that expired token session are not impacting the user.

# User Story

**AS A** user
**I WANT TO** my Otomi shell to be automatically pruned
**SO** There are no tty Pods that consuming my cluster resource

# Acceptance criteria

**GIVEN** I opened my Otomi SHELL
**WHEN** TTL  of Two hours lapses 
**THEN** this the Kubernetes resources related to this Otomi Shell are pruned 

**GIVEN** there is a TTL configurable
**WHEN** user set different TTL value 
**THEN** the counters are adjusted for new Otomi shell sessions

# Definition of done

- [ ] Relevant PRs are merged
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer
- [ ] Short demo video recorded and stored on google drive (if applicable)

**Comment by ferruhcihan** [comment]
To determine whether a shell pods are running and actively using resources, we can use one of the following techniques. 

1. We can check the logs of a container within the pods to see if they are actively processing data or performing tasks.
`kubectl logs <pod-name>`

2. We can also exec into the pod's container to run commands and inspect their internal state.
`kubectl exec -it <pod-name> -- /bin/bash`
Once inside the container(s), we can use tools like `top` or `ps` commands to check if they're active.

3. We can set up monitoring and metrics collection for our shell pods using tools like Prometheus and Grafana.

With these methods, we can understand whether the pods are actively used or not by comparing them with their previous status. By making this comparison at certain intervals (30 mins, 1 hour etc), we can terminate the shell pods if they are not used.
