### ISSUE TITLE
Default Helm chart values for workloads

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1244]
# WHY

Provide a context behind this user story that explains why it is needed.

# User Story

**AS A** user

**I WANT TO** obtain the default values in the values editor in otomi-console

**SO** I can easily edit it and remove parts that I ma not interested in.

# Acceptance criteria

**GIVEN** a user **creates** a workload with a custom Helm chart (so no workload values are defined yet)
**WHEN** user enters the correct chart repo URL and optional path
**THEN** otomi-api fetches the values.yaml file of this Helm chart and thus
**WHEN** user goes to the values editor
**THEN** user can see and edit the content of the values.yaml file

**GIVEN** a user **creates** a workload with a custom Helm chart (so no workload values are defined yet)
**WHEN** user enters incorrect chart repo URL and optional path
**THEN**  user is informed about it

# Definition of done

- [ ] Relevant PRs are merged
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer
- [x] Short demo video recorded and stored on google drive (if applicable)

**Comment by ferruhcihan** [comment]
Uploaded demo video:
https://drive.google.com/file/d/1qXNOiTRBeK7k0U4SayxWvgGcNd83q-e_/view?usp=drive_link

**Comment by j-zimnowoda** [comment]
I was testing it with the following values:
url: https://github.com/crossplane/crossplane
path: crossplane/cluster/charts/crossplane

but I could not make it work

**Comment by j-zimnowoda** [comment]
well done!
