### ISSUE TITLE
Unable to setup kubectl due to UI Form error

### ISSUE THREAD

**Issue by LUK3-DEV** [redkubes/otomi-core#1261]
**Describe the bug:** (a clear and concise description of what the bug is)

When I try to specify my full kubernetes api, I click save and get a weird form error that I cannot fix

**To Reproduce**

1. Go to 'settings > cluster > API Server input'
2. Input full qualifying API URL
3. click save

Get form validation error in browser console 
{
    "name": "additionalProperties",
    "property": "['k8sVersion']",
    "message": "is an invalid additional property",
    "params": {
        "additionalProperty": "k8sVersion"
    },
    "stack": "['k8sVersion'] is an invalid additional property",
    "schemaPath": "#/additionalProperties"
}

**Expected behavior:** (a clear and concise description of what you expected to happen)

I should be able to add this so that I can download KUBECFG which is blanked out

**Screenshots:** (if applicable, add screenshots to help explain your problem)
![image](https://github.com/redkubes/otomi-core/assets/71877333/87a7289b-22bd-4c39-ab8e-12d20c1368b8)

**Cluster(s):**

digital ocean

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

- OS: MacOS
- Browser : Brrace
- Version v0.25.0

**Comment by ElderMatt** [comment]
Because of no further comments have been placed in the last 2 months, I will now close this issue.
