### ISSUE TITLE
Document OIDC credentials rotation

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1263]
# WHY
To accelerate this operation and have a background for the process automation

# User Story
**AS A** operator

**I WANT TO** rotate OIDC  and keycloak passwords

**SO** I can follow the security requirements of my organisation

# Acceptance criteria

**GIVEN** active Otomi instance 
**WHEN** I need to rotate OIDC credentials
**THEN** I follow the [documentation](https://redkubes.atlassian.net/wiki/spaces/KB/pages/5297209345/OIDC+credentials+rotation)

# Definition of done
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer

**Comment by staticvoid255** [comment]
[Completed and added to Operations Manual](https://redkubes.atlassian.net/wiki/spaces/KB/pages/5297209345/OIDC+credentials+rotation)

**Comment by j-zimnowoda** [comment]
I added few comments in the docs

**Comment by staticvoid255** [comment]
Updated according to your remarks, think this can be closed now
