### ISSUE TITLE
Follow the kubernetes support release model

### ISSUE THREAD

**Issue by Roguito** [redkubes/otomi-core#1271]
https://kubernetes.io/releases/

"The Kubernetes project maintains release branches for the most recent three minor releases (1.28, 1.27, 1.26). Kubernetes 1.19 and newer receive [approximately 1 year of patch support](https://kubernetes.io/releases/patch-releases/#support-period). Kubernetes 1.18 and older received approximately 9 months of patch support."

This is a requirement in my particular case due to using k0s to automate cluster management which also follows the kubernetes release model.

At the time of this request, deploying otomi:
"The cluster with kubernetes version 1.27 is utilizing a less compatible version for otomi. For optimal performance and features, we recommend using one of our supported versions: [1.24, 1.25, 1.26]."

This does not follow the kubernetes release and support guidelines.

**Comment by j-zimnowoda** [comment]
Hello @Roguito,

I appreciate your message and the points you've raised. We've been deliberating extensively on the number of Kubernetes (k8s) versions we should support for each Otomi release. This decision involves several factors, such as the variance in k8s versions, compatibility with community charts/operators, and the tools that rely on kubectl (such as helmfile and Helm), all of which impose constraints on the supported k8s versions.

As we've dug deeper into this, we've realized that accommodating a larger number of k8s versions significantly complicates our implementation and can potentially compromise the quality of our product. Nevertheless, we also understand the importance of providing enough supported Kubernetes versions to enable our customers to smoothly upgrade their k8s clusters within the scope of a given Otomi version.

Therefore, considering all these factors, we have decided to commit to supporting three minor versions of Kubernetes (e.g., 1.24, 1.25, and 1.26) for each Otomi release.

Regarding your initial query about supporting k8s 1.27:
- Support for k8s 1.27 is scheduled to be available by the end of September.
- We are planning to introduce support for k8s 1.28 by the end of November.

I hope this clarifies our approach to Kubernetes version support in Otomi. If you have any further questions or concerns, please feel free to reach out.

**Comment by j-zimnowoda** [comment]
Supported K8s versions can be found at: https://otomi.io/product/roadmap

**Comment by ElderMatt** [comment]
Because of no further comments have been placed in the last month, I will now close this issue. Feel free to reach out again if you think this is still an issue.
