### ISSUE TITLE
Loki IAM role configuration for accessing AWS S3 service

### ISSUE THREAD

**Issue by armantur** [redkubes/otomi-core#1272]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

Loki object storage access configuration is managed by Otomi. Currently, Loki supports only IAM credentials (access key/secret access key) for accessing AWS S3. This implementation adds additional complexity to rotating credentials and creating/managing Loki IAM service users.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

It would be great to have the ability to configure Loki to use the IAM role instead of IAM credentials to access AWS S3 service. 

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

I don't think there is a better alternative other than using the IAM role.

**Additional context** Add any other context or screenshots about the feature request here.

Loki helm chart doesn't allow to overwrite IAM credentials configuration with IAM role even if _rawValues are used.

**Comment by j-zimnowoda** [comment]
Hi @armantur this feature has been implemented and released (https://github.com/redkubes/otomi-core/releases/tag/v1.0.0). 

I am closing this issue but feel free to reopen it if there is still something to do about it.
