### ISSUE TITLE
Migrate platform pipeline from Drone to Tekton

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1294]
# WHY

Provide a context behind this user story that explains why it is needed.

# User Story

**AS A** user 
**I WANT TO** see Otomi deployment pipeline in Tekton dashboard
**SO** so I can see logs and status

# Acceptance criteria

**GIVEN** Tekton triggers and Tekton dashboard
**WHEN** a user clicks Deploy Changes
**THEN** Tekton pipeline starts
**AND** I can see its status in Otomi Console

**GIVEN** Tekton status in Otomi core
**WHEN** when I click on it 
**THEN** I navigate to  Tekton dashboard (platform app) 
**AND** I can see its pipeline logs

**GIVEN** Drone being deprecated in Otomi
**WHEN** I click Drone icon. 
**THEN** I will see information about Drone app being deprecated and link to Tekton Dashboard
**AND** I can click "I understand" and navigate to Drone

# Definition of done

- [ ] Relevant PRs are merged
- [x] Tested by peer
- [ ] Updated documentation reviewed by peer
- [ ] Short demo video recorded and stored on google drive (if applicable)

**Comment by Ani1357** [comment]
Proposal: 2 devs needed, 1 frontend + 1 infra
  - Frontend est 5SP Infra est 21SP

If drone is being deprecated what would be the impact on customers using it for their pipelines?

**Comment by j-zimnowoda** [comment]
> If drone is being deprecated what would be the impact on customers using it for their pipelines?
No. We can plug out drone from helmfile but still keep the deployed release.

> Proposal: 2 devs needed, 1 frontend + 1 infra
sure
> Infra est 21SP
Could you explain your reasoning behind this estimate ?

**Comment by j-zimnowoda** [comment]
1. how to run Otomi CLI in Tekton step? @j-zimnowoda 
2. how to automate webhook creation run Gitea (Otomi-tasks). Which REST API endpoint should I use?  @ElderMatt

**Comment by j-zimnowoda** [comment]
3. How to inform users that sth is deprecated ? @frontend

**Comment by Ani1357** [comment]
Created otomi-pipelines chart which will include all needed resources for running the otomi pipeline
Updated the tekton-pipelines chart to the latest version
Reworked existing pipelines(build pipelines) to use api version V1
Updated tekton dashboards to the latest version
Todo: 
Refactor the tekton-pipelines helm chart. Currently the tekton-pipelines helm chart is not in sync with the their latest release.

**Comment by j-zimnowoda** [comment]
well done!
