### ISSUE TITLE
Provide a Template catalog in Otomi Console

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1295]
# WHY

Developers need golden deployment paths for their applications. The charts provided by Otomi are not always what a user needs. By providing the option to add (tempate) charts to Otomi, admins can provide custom Golden path templates to users. A user then selects a template from the catalog and use it to create a workload

# User Story

**AS A** developer
**I WANT TO** use predefined workload Helm charts from the template catalog
**SO** I can easily deploy my applications

This is how it should look like from a developer perspective: A user can go to the templates catalog in Otomi Console. The user can see the details of a template (loaded in using the chart.yaml in the chart folder) and can click on `Create workload from template`. Then the form for a new (BYO) workload is shown and a user can add a name (but does not need to will in the repo URL). The user can then adjust values and submit.

**AS A** platform engineer
**I WANT TO** manage template catalog for my organisation
**SO** development teams can leverage golden path templates for deploying their applications in Otomi

This is how it should look from a platform admin perspective: An admin creates a golden template Helm chart. In the chart.yaml, the admin can add chart specific properties. The admin then adds the chart to the `otomi/charts` repo in Gitea. Otomi will then add the template in the template catalog in Otomi Console and show details of the template based on the chart.yaml.

# Acceptance criteria

**GIVEN** Default (helm) template catalog hosted on GitHub under redkubes organisation in the otomi-charts repo
**WHEN** I install Otomi for the first time
**THEN** the default template catalog is cloned to a private git repo (called `otomi/charts`) in Gitea.

**GIVEN** Gitea repository that can host Helm charts in git repository
**WHEN** I create a workload
**THEN** I can select a Helm chart from the template catalog in Otomi console and click on `Create workoad from template`

**GIVEN** Default workload catalog hosted on GitHub under redkubes organisation
**WHEN** I upgrade Otomi to a new version
**THEN** the default workload catalog is uploaded to the otomi/charts repo in Gitea

# Definition of done

- [ ] Relevant PRs are merged
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer
- [ ] Short demo video recorded and stored on google drive (if applicable)

**Comment by Ani1357** [comment]
More info is needed. Please provide more info on the example use case?

**Comment by j-zimnowoda** [comment]
I enriched user story section. Is it enough to info?

**Comment by j-zimnowoda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-core/1295?planning-poker) with Zenhub @Ani1357 @dennisvankekem @ElderMatt @ferruhcihan @staticvoid255 @srodenhuis

**Comment by srodenhuis** [comment]
I changed the issue and added some more information. I hope this gives you all a good idea about what we like to achieve here.

**Comment by srodenhuis** [comment]
I propose to use (almost) the same properties in the Chart.yaml to show the template in the Template Catalog:

```
title: Deployment with database # this will be shown as the name of the template in the catalog
appVersion: 2.5.3
maintainers: platform team
repo: # the link to the chart in the otomi/charts repo
icon: # link to an icon to use for the template
relatedLinks:
  - https://mycompany.com/docs/hello
description: A description of the chart # shown in the catalog
instructions: # additional instructions
```
In the docs we will explain how to use the Chart.yaml to show the template in the catalog

**Comment by j-zimnowoda** [comment]
# Test case 1
```
cd values
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm pull crossplane-stable/crossplane --version 1.14.0
tar -xzf crossplane-1.14.0.tgz 
git add crossplane-1.14.0
git push
```
