### ISSUE TITLE
metrics-server already exists?

### ISSUE THREAD

**Issue by Roguito** [redkubes/otomi-core#1313]
**Describe the bug: metrics-server is already installed as part of other on-prem and cloud stacks

**To Reproduce**
minimal install instructions.
helm install otomi otomi/otomi --set cluster.name=s9 --set cluster.provider='custom'

**Expected behavior: successful helm install

STDERR:
  Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "metrics-server" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "metrics-server"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

COMBINED OUTPUT:
  Release "metrics-server" does not exist. Installing it now.
  Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "metrics-server" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "metrics-server"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
    at hfCore (/home/app/stack/dist/src/common/hf.js:44:30)
    exit code: 1
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Cluster(s):
- Cloud: custom
- Cluster: s9

**Comment by Roguito** [comment]
Seems my particular issue is that I've gone down or ended up in the SUSE k8s ecosystem and am running a 'custom' k3s/rke2 provisioned bare metal lab and metrics-server is already deployed to provide metrics to my Rancher Manager installation.

https://rke.docs.rancher.com/config-options/add-ons/metrics-server#:~:text=By%20default%2C%20RKE%20deploys%20Metrics,Metrics%20Server%20as%20a%20Deployment.

**Comment by j-zimnowoda** [comment]
Hey Roguito,
You can disable metrics server by specifying the following configuration while installing Otomi Helm chart
```
apps:
    metrics-server:
        enabled: false
```

**Comment by j-zimnowoda** [comment]
Hi Roguito,
I am closing this issue as it has been answered. If you have any further questions feel free to reopen it.
