### ISSUE TITLE
Support kubernetes v1.26.6

### ISSUE THREAD

**Issue by RafMo20D** [redkubes/otomi-core#1356]
# Requirments

Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
otomi:
- cluster: Additional property k8sVersion is not allowed

provider=azure

**Comment by j-zimnowoda** [comment]
@RafMo20D 
We have removed `k8sVersion` property 
Please remove it from you values.

**Comment by RafMo20D** [comment]
https://github.com/redkubes/quickstart/tree/main/azure
