### ISSUE TITLE
Render workload values including comments

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1381]
**Is your feature request related to a problem? 
Currently, the otomi-api fetches the values.yaml file and convert its content using `yaml` package. This package converts a string to the object therefor it removes the YAML comments.

Team users can not see comments in values editor. 

**Describe the solution you'd like** 
Maybe we can show the full values.yaml (including comments) of a chart in the developer catalog.
That said we need to se if it is possible to store the workload values with comments.

**Comment by j-zimnowoda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-core/1381?planning-poker) with Zenhub @Ani1357 @dennisvankekem @ElderMatt @ferruhcihan

**Comment by j-zimnowoda** [comment]
After discussion with @ferruhcihan we agreed that Values editor will render comments on the very first time workload is created. It means that comments will not be stored in the workload values file. Out hypothesis is that users needs the most the comments while installing the Helm chart. Later they are even not welcome as they blur the configuration file, making it unnecessary long.

**Comment by j-zimnowoda** [comment]
In the values editor page we could add a link to the `gitea.<clusterSuffix>/otomi-charts/<chart-name>/values.yaml` file, so user can easily navigate and see documentation.

**Comment by ferruhcihan** [comment]
We can add the link in the values editor page, it might be useful when the user wants to see the documentation again
