### ISSUE TITLE
Deploy Otomi upon new release

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1392]
**Is your feature request related to a problem? Please describe.** 
Ensure that artefacts are ready

**Describe the solution you'd like** 
After the `chart-release` Github Actions job succeeds, start a job that deploys new Otomi Helm chart from Helm registry.

**Comment by j-zimnowoda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-core/1392?planning-poker) with Zenhub @Ani1357 @dennisvankekem @ElderMatt @ferruhcihan

**Comment by dennisvankekem** [comment]
needs refinement

**Comment by j-zimnowoda** [comment]
@dennisvankekem could you elaborate ?

**Comment by j-zimnowoda** [comment]
We will test it during the patch release

**Comment by j-zimnowoda** [comment]
well done!
The test has been triggered.
https://github.com/redkubes/otomi-core/actions/runs/7502056677/job/20424109374
