### ISSUE TITLE
ArgoCD pod scheduling does not follow otomi.nodeSelector 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1467]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Create cluster with two nodepools
2. Deploy Otomi with `otomi.nodeSelector` set to the first pool.
3. Observe that affinity is added to the `spec` of the argocd deployments (`/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms`), but that the `values`

```
key: <label-name>
operator: In
values: 
- <label-value>
```

is added over and over again, resulting is a loop where the Pods are created and then terminated again.

**Expected behavior:** (a clear and concise description of what you expected to happen)
ArgoCD workloads are deployed on pool specified by  `otomi.nodeSelector` selector

**Comment by srodenhuis** [comment]
It's not needed to add a second node pool to reproduce this bug. Just set the nodeSelector and then delete one of the argocd pods.

**Comment by j-zimnowoda** [comment]
waiting for release
