### ISSUE TITLE
Increase timeout for Keycloak to be ready during deployment

### ISSUE THREAD

**Issue by merll** [redkubes/otomi-core#1474]
When deploying Otomi to some cloud hosting providers, the installation fails during the Keycloak setup (e.g. `wait-for-otomi-realm`). Most of the time, this is due to the updated DNS entries not being able to resolve (at all or in time). In some other cases, the certificate of Keycloak is rejected as self-signed.

Some of the DNS resolution issues are caused by configuration. However, increasing the timeout could account for some lag in the updates.

Additionally, users should be made aware of common configuration issues by adding a checklist of prerequisites to the installation docs, e.g. providing a valid email address when using Letsencypt, testing DNS beforehand (especially NS entries).

**Comment by j-zimnowoda** [comment]
needs retesting
