### ISSUE TITLE
istio upgrade to 1.9

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#164]
Istio telemetry is not packaged anymore from 1.8 onwards. Read https://istio.io/latest/blog/2020/addon-rework/ for the rework that needs to happen. In this story we will upgrade istio to 1.9 only. Rest of the work will come in other stories.

Expected outcomes:
- [ ] Istio updated to 1.9 

Remaining work:

- Kiali operator added and configured
- Jaeger chart added and configured
- Grafana from prometheus-operator chart configured to also use istio source
- Grafana-dashboards chart to include the istio dashboards
- Prometheus from prometheus-operator configured to include all the istio targets

Tasks:

- [ ] analyze impact: https://istio.io/latest/news/releases/1.9.x/announcing-1.9/
- [ ] istio CRs in the `team-ns` chart are updated to reflect highest supported version
- [ ] `values/istio-operator-raw.gotmpl` is updated to be compatible with the new `istio-operator` CRD format (if changed)

**Comment by Morriz** [comment]
Nice one for you @svatwork ;)

**Comment by svatwork** [comment]
Yes, sounds like a proper challenge after team jobs

**Comment by svatwork** [comment]
Ok, I will become more mindful of [pull request vs issue etiquette](https://stackoverflow.com/questions/9563881/etiquette-of-github-contributing-pull-requests-vs-new-issue). Hope someone will clarify then if I post a comment here.

I was working on #262 (Kiali operator added and configured)

I have a basic configuration of Kiali Operator, but that's of course not sufficient. But I don't know what is under the definition of done for this story (or for any story adding new components), is it a basic configuration like this or are there any special requirements for integrating it?

On the top of my head:

- [ ] Refactor this chunk from values/istio-operator-raw.gotmpl:
```kiali:
          enabled: {{ $ia | get "kiali.enabled" true }}
          k8s:
            priorityClassName: "otomi-critical"
            resources:
              {{- with $i | get "resources.kiali" nil }}
                {{- toYaml . | nindent 14 }}
              {{- else }}
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1
                {{- end }}
      values:
        kiali:
          contextPath: '/kiali'
          dashboard:
            auth:
              strategy: anonymous #openid
              # openid:
              #   issuer_uri: {{ $keycloakBase }}
              #   client_id: {{ $v.oidc.clientID }}
            jaegerURL: https://{{ $appsDomain }}/tracing/
            grafanaURL: https://{{ $appsDomain }}/grafana-istio/
```
- [ ] Set new Istio version (breaking change), maybe work on #259 first.
- [ ] Configure Kiali CR (https://kiali.io/documentation/latest/installation-guide/#_create_or_edit_the_kiali_cr)
- [ ]  Expose values.yaml in values-schema.yaml (and then we should make a distinction between what should be default and what should be configurable).

My original question: am I forgetting something in these requirements?

@redkubes/devops

**Comment by Morriz** [comment]
That seems ok to me. One addition. Since we can deploy kiali via CR now, we can offer it to teams as well. Please add the CR to `charts/team-ns` and allow for teams to turn it on (default off) from the console's new app settings (coming soon).

**Comment by Morriz** [comment]
Do make sure to have the CR turned on via `charts.kiali.enabled` (we might rename `charts` to `apps` later as that is more fitting) for team-admin in `helmfile.d/helmfile-15.ingress-core.yaml` by adding a value 

I suggest the following renaming steps:

- `helmfile-15.ingress-core.yaml` > `helmfile-15.team-ns-admin.yaml`
- `helmfile-30.admin.yaml` > `helmfile-30.admin-apps.yaml`

**Comment by j-zimnowoda** [comment]
@Morriz the team feels that this story is way too big.
Could you split it into smaller parts that represents each application separately?
I am also wondering if Knative shall be also upgraded together with Istio?

**Comment by Morriz** [comment]
If that can be delivered separately, great. Go ahead and cut it up as you see fit...

**Comment by Morriz** [comment]
Simplified to only upgrade istio in this story.

Rest will come as separate stories.

**Comment by j-zimnowoda** [comment]
@Morriz you are asking to integrate istio **1.9** with knative **0.21**

BUT the knative documentation specifies istio **1.8.2** to be compatible with  **knative 0.21**
See: https://knative.dev/v0.21-docs/install/installing-istio/#supported-istio-versions

Could you double check it.

**Comment by svatwork** [comment]
Looks like it is supported (but not stable). Maybe it was not updated in the documentation. For reference:

- https://github.com/knative-sandbox/net-istio/pull/515
- https://knative.dev/blog/2021/02/26/version-v0.21-release/#serving-v021
