### ISSUE TITLE
Implement harbor oidc admin awareness

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#176]
Coming in the harbor 2.2.0 release: option to configure oidc group that will become superadmin. Please also rewrite harbor task to configure that.

**Comment by j-zimnowoda** [comment]
#109 looks like duplicate

**Comment by Morriz** [comment]
@j-zimnowoda can you move it to tasks repo rhen and update info?

**Comment by svatwork** [comment]
I can't find it, what's the source for this? I looked at https://github.com/goharbor/harbor/issues?page=2&q=is%3Aissue+is%3Aopen+label%3Atarget%2F2.2.0.

**Comment by Morriz** [comment]
> https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/otomi-api/109 looks like duplicate

True. Closing in favor of the previous one. It has the link to the issue and announcement to publish the feature in 2.2.0
