### ISSUE TITLE
otomi cli improvements

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#181]
Improvements:
- We can get rid of the active env vars CLUSTER & CLOUD by getting them from kubeconf current context:
  - see if it matches regex `$customer-$cloud-$cluster`, then extract

Implications:
- `otomi template` and `otomi values` might not have a cluster yet, so they still should bork and ask to provide CLOUD & CLUSTER

**Comment by svatwork** [comment]
I actually like this idea a lot, it would improve the new user experience. Why was it closed?

**Comment by Morriz** [comment]
It is already part of the new PR by @Dunky13. Where are those requirements found for `otomi configure`? We wrote them up somewhere but I see no more PR.

**Comment by Dunky13** [comment]
There's no PR for it yet.
It's related to #274 but put the development of otocomplete on hold. I spent 3 full days on about 20 lines of code and wasn't making any progress. autocomplete for zsh is tricky when moving into several levels. The `otomi configure` that @Morriz mentioned is scripted there as well, but as dev is on hold for now, it hasn't been pulled into otomi.
