### ISSUE TITLE
Deploy cluster from scratch with disabled encryption

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#194]
The goal of this task is to evaluate disabled encryption feature.

**Comment by Morriz** [comment]
We need proper docs explaining all prereqs like dns access as well. On it!

**Comment by j-zimnowoda** [comment]
Indeed. I am writing down some notes about it.

**Comment by j-zimnowoda** [comment]
Few bullets: 
A domain name under which otomi container platform will be exposed.
- dns domain managed by azure/aws/google
- service account to manage DNS records
Value settings:
- external-dns.yaml (DNS zone and domain)
- cert-manager.yaml (DNS provider)

Usability concerns:
- there is no explicit connection betwwen cloudDnsKey (secret.settings.yaml) and serviceAccountSecretRef (cert-manager.yaml). See how it is solved for external-dns.

**Comment by Morriz** [comment]
I believe the same dns service account is usable by cert-manager, so in essence only that is required for the platform to work without external loadbalancer, the OOTB setup (Out Of The Box)

Will add docs now to address that

**Comment by Morriz** [comment]
closing this task as discussions here should revolve around code

**Comment by Morriz** [comment]
@j-zimnowoda I would really not like to repeat that we should NOT use github issues for these discussions. We have github templates for issues: bug, feature, story, task (all related to coding)...so please only create those type of issues here, and move discussions to their respective platform (we use slack for that)

**Comment by Morriz** [comment]
we should ask to use slack for free now that we are open source!

**Comment by j-zimnowoda** [comment]
So what is the purpose of comment here?
