### ISSUE TITLE
Missing resources from helmfile.tpl/helmfile-init.yaml

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#201]
Currently templates from `helmfile.d` are rendered and validated by the following commands `otomi template`, `otomi validate-templates`

The `helmfile.tpl/helmfile-init.yaml` is not taken into account but is used by `otomi deploy` command.

The `otomi template` and `otomi validate-templates` should take into account the additional `helmfile.tpl/helmfile-init.yaml` file in order to  ensure quality of all the manifests that are produced.

**Comment by j-zimnowoda** [comment]
The solution has been already provided.
The `otomi validate-templates` takes  helmfile.tpl/helmfile-init.yaml into account

**Comment by Morriz** [comment]
So can this be closed then @j-zimnowoda ?

**Comment by j-zimnowoda** [comment]
Yes
