### ISSUE TITLE
simple test to check bootstrap oneliner

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#203]
**Is your feature request related to a problem? Please describe.**

When people use the bootstrap one-liner mentioned on [this page](https://redkubes.github.io/otomi/docs/setup), we want to make sure that it works correctly.

**Describe the solution you'd like**

The script has a unit test that checks if the env folder is created. The flag skip_demo_files will be removed. Furthermore, the repository has integration tests that capture script behaviour about multiple executions and exit codes.

**D.o.d.**

- [x] Multi-staged build in the Dockerfile, making it portable.
- [x] bin/tests/*.sh called by [bats](https://github.com/bats-core/bats-core).
- [x] Check if the env folder is created (unit tests). 
- [x] Check multiple executions and exit codes (integration tests).
- [x] Refactor such that the flag skip_demo_files will be removed.
- [ ] Write documentation.

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by svatwork** [comment]
**Is your feature request related to a problem? Please describe.**

When people use the bootstrap one-liner mentioned on [this page](https://redkubes.github.io/otomi/docs/setup), we want to make sure that it works correctly.

**Describe the solution you'd like**

The script has a unit test that checks if the env folder is created. The flag skip_demo_files will be removed. Furthermore, the repository has integration tests that capture script behaviour about multiple executions and exit codes.

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by svatwork** [comment]
- [ ] Multi-staged build in the Dockerfile, making it portable.
- [ ] bin/tests/*.sh called by [bats](https://github.com/bats-core/bats-core).

**Comment by svatwork** [comment]
I will write documentation once the pull requests have been approved.
