### ISSUE TITLE
Run Github Actions locally with https://github.com/nektos/act

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#214]
**Is your feature request related to a problem? Please describe.** 

It would be quite convenient to be able to run the Github Actions locally. This will improve iteration speed. Right now, to test what I've committed, I have to wait for the Github Action to end. It can take quite a while. Moreover, to test my build, I have to commit first, which creates a lot of unnecessary commits where if the build fails, you have to fix or revert something in a new commit. 

**Describe the solution you'd like** 

It would be convenient to use https://github.com/nektos/act. You can run local workloads, so when the build passes locally, you can be more certain that the build will pass remotely as well. It requires some work however, I didn't spend too much time on it but the main problem to get it working is that there's no access to most of the variables that are used by .github/workflows/main.yml. 

You can add the variables, but I don't have access to them right now. Of course, it doesn't make sense to add the secrets in a json file. The documentation is over here: https://github.com/nektos/act#events. You can simulate the event because with `act -e event.json` it will be able to retrieve those parameters as if it were on Github.

**Describe alternatives you've considered** 

An alternative would be to have a self-hosted Github Actions runner with more resources. However, then you still need to log in to the machine to check the output. 

**Additional context**

Here's a start with the event.json file format that can be used:

```
{
    "ref": "refs/heads/feature",
    "head_commit": "run: act -e .github/workflows/main-event.json"
}
```

Here's some of the documentation:

- https://github.com/nektos/act
- https://developer.github.com/webhooks/event-payloads/#push
- https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows

**Comment by Morriz** [comment]
Yeah, I know the frustration, but most issues are with configuration out of our control (credentials, permissions), so this solution does not help with that. Since we try to keep pipelines small and dumb, I would focus on keeping it that way, and maybe even make them more DRY.

**Comment by Morriz** [comment]
I believe for every repo  we would like to see one simple pipeline pushing buttons on the repo:

1. checkout
2. build-test-push-cache (all in dockerfile)
3. retag-and-publish
4. release

And since we already have that structure, all I can see as improvement is taking code out of the steps and putting them in scripts in the repo. But this has no prority right now.

**Comment by Morriz** [comment]
Closing this as I see no value now or in the future.
