### ISSUE TITLE
kubectl get po error: error loading config file "/Users/$user/.kube/config": read /Users/$user/.kube/config: is a directory

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#218]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**
1. `docker run -e ENV_DIR=$PWD -v $PWD:$PWD otomi/core:latest bin/bootstrap.sh`
2.` kubectl get po`
3. `kubectl get po error: error loading config file "/Users/sebastiaanverbeek/.kube/config": read /Users/sebastiaanverbeek/.kube/config: is a directory`

**Expected behavior:**

It seems some files are changed into directories. After a fresh install of the Otomi platform I expect to see "connection refused" because I haven't added any Kubernetes clusters yet to my kubeconfig.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**
 - Cloud: -
 - Cluster: -

**Versions:** (seen in console's `/settings`)
 - Core Version 0.11.45
 - Console Version: -
 - API version: -

**Desktop:** (if relevant)
 - OS: MacOS 
 - Browser -
 - Version: 10.14.6

**Smartphone:** (if relevant)
 - Device: -
 - OS: -
 - Browser -
 - Version: -

**Additional context:** (add any other context about the problem here)

**Comment by Morriz** [comment]
Can this be fixed by setting the paths correctly? (Mapping the folder instead of the file in it.) If so then please go ahead

**Comment by Morriz** [comment]
@svatwork ?

**Comment by svatwork** [comment]
I can't reproduce it, let's close it for now.
