### ISSUE TITLE
incorrect values for azure-dev environment

### ISSUE THREAD

**Issue by rawc0der** [redkubes/otomi-core#221]
**Describe the bug:**
`otomi template` not working properly due to incorrect values for Azure Dev environment.

**To Reproduce**
1. Open `otomi-core` repo in a Terminal window:
2. export CLOUD=azure CLUSTER=dev
3. otomi validate-templates true
4. See errors

**Expected behavior:** 
All charts should be templated correctly but the following chart values are broken: **cert-manager-raw**, **external-dns**, **ingress-azure**

**Error Logs:** 
```
in helmfile.d/helmfile-20.ingress.yaml: 3 errors:
err 0: failed to render values files "../values/cert-manager/cert-manager-raw.gotmpl": failed to render [../values/cert-manager/cert-manager-raw.gotmpl], because of template: stringTemplate:8:16: executing "stringTemplate" at <$cm.provider.azure.azuredns>: map has no entry for key "azure"
err 1: failed to render values files "../values/external-dns/external-dns.gotmpl": failed to render [../values/external-dns/external-dns.gotmpl], because of template: stringTemplate:21:10: executing "stringTemplate" at <$dns.azure>: map has no entry for key "azure"
err 2: failed to render values files "../values/ingress-azure/ingress-azure.gotmpl": failed to render [../values/ingress-azure/ingress-azure.gotmpl], because of template: stringTemplate:17:19: executing "stringTemplate" at <$i.armAuth.secretJSON>: map has no entry for key "armAuth"
```
**Cluster(s):**
 - Cloud: azure
 - Cluster: dev

**Versions:** 
 - Core Version master

**Comment by rawc0der** [comment]
@Morriz I found what is causing this issue.
The problem is from sops and this is the only file from the list which is not decrypting correctly. Still working on figuring out what is the actual problem.

```
Decrypting ./clouds/azure/secrets.overrides.azure.yaml
Error decrypting tree: Error walking tree: Could not decrypt value: Could not decrypt with AES_GCM: cipher: message authentication failed
Error: plugin "secrets" exited with error
```

**Comment by rawc0der** [comment]
After retrying the `otomi decrypt` a couple of times it worked.
I traced the issue of broken values to the following file:  `VALUES-REPO/env/secrets.settings.yaml`
Here the **azure** and **google** blocks were top level properties and I guess they should have been under **clouds**.
```
clouds:
    azure:  ---
    google: ---
```
After fixing this, templates are rendering. @Morriz Should I push the fix to values repo?

**Comment by rawc0der** [comment]
Actually for the whole repository to work again a fix to `values/cert-manager-raw.gotmpl` is needed to access values from the same structure.

line 22: `      key.json: "{{ $v | getOrNil "clouds.google.cloudDnsKey" | b64enc }}"  `

**Comment by rawc0der** [comment]
Sorry, the values repo is ok, problem is comming from sops not decrypting that file and this gives templating errors hard to debug.
Closing this issue as file decryption is working after couple of retries.

**Comment by Morriz** [comment]
> After retrying the `otomi decrypt` a couple of times it worked.
> 
> I traced the issue of broken values to the following file:  `VALUES-REPO/env/secrets.settings.yaml`
> 
> Here the **azure** and **google** blocks were top level properties and I guess they should have been under **clouds**.
> 
> ```
> 
> clouds:
> 
>     azure:  ---
> 
>     google: ---
> 
> ```
> 
> After fixing this, templates are rendering. @Morriz Should I push the fix to values repo?

Yes, those props are now top level. That is by design. So no change needed.

I recommend to regularly do a `docker pull otomi/core:master` and `docker pull otomi/core:latest`. After that do `otomi bootstrap` to get the latest `values-schema.yaml`.
