### ISSUE TITLE
$ otomi image v0.x.y 

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#226]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

I would like to specify the image when I run an otomi command. It's not that I would like to run previous versions all the time, but it's nice that I could use my own docker image when I'm working in a feature branch.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

E.g.

```
otomi image v0.x.y
otomi diff
# Pulling otomi/core:v0.x.y 
```

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

I can keep running otomi/core:latest but it's a bit cumbersome to change the tags in docker manually when I want to use a different version, or a local version for that matter. I can also edit the otomi script manually, which works fine for now (e.g. I'm working on a feature branch that uploaded a new image on Dockerhub add-exec):

```
function set_otomi_image() {
  cmd_image="otomi/core:add-exec"
  return 0
}
```

**Comment by Morriz** [comment]
When working on a feature branch you will automatically see a container tag pushed from that feature branch name. You can set it in the values repo and it will be picked up.

We all use that functionality for a long time and it suits our needs. Closing this issue.

**Comment by Morriz** [comment]
Plus, when working on otomi-core directly, the working dir is mounted and your code changes will be deployed as is.
