### ISSUE TITLE
As a developer, I would like to verify if chart values are rendered as expected

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#231]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
The final chart values are result of complex merging, templating and logic operations (performed at values/<chart>/*.gotmpl files)
As a developer, I would like to verify if chart values are rendered as expected.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
The new helmfile command `helmfile write-values` provides the following functionality:
> write values files for releases. Similar to `helmfile template`, write values files instead of manifests.
The otomi-core could leverage it for chart values rendering tests, by comparing `helmfile write-values` output with prerendered chart values.
 
**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.
n/a

**Additional context** Add any other context or screenshots about the feature request here.
The chart values file can be generate in predictable fashion, e.g.:
```
helmfile -e $CLOUD-$CLUSTER -l name=harbor write-values --skip-deps --output-file-template='{{ .Release.Name}}.yaml'       
```

**Comment by Morriz** [comment]
> helmfile -e $CLOUD-$CLUSTER -l name=harbor write-values --skip-deps --output-file-template='{{ .Release.Name}}.yaml'

Seems to me that you are asking to modify helmfile, so please take it there?

**Comment by j-zimnowoda** [comment]
Noooooo, there is already ` write-values` command in helmfile.
