### ISSUE TITLE
Change values-schema.yaml to values-schema.json

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#241]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

I have much more success with validating JSON files against YAML files instead of using https://github.com/redhat-developer/yaml-language-server. There are a couple of reasons for this. I just want to have a discussion about it and if it's not a good idea then so be it.

- It can break sometimes, e.g. https://github.com/redhat-developer/yaml-language-server/issues/356.
- It doesn't function smoothly in VSCode when using autocompletion. E.g.:

If I use the JSON version as in my `otomi-values` repository:

```
"yaml.schemas": {
    "http://json-schema.org/draft-07/schema#": ".vscode/values-schema.json",
    ".vscode/values-schema.json": "env/*.yaml"
  }
```
Then it shows:

![Screenshot 2020-12-11 at 13.50.51.png](https://images.zenhubusercontent.com/5fb3eb135472cfeda30e7684/69a1eaa2-fd64-49d0-8bc8-fd13878a29b0)

And that makes sense because the schema actually requires keys for the first indices. But it will (it should) throw an error in any newly created .yaml file in the `otomi-values` directory.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

I would like some specific changes:
- `values-schema.yaml` will be `values-schema.json` only.
- in `otomi-core` and `otomi-values` this values-schema.json is applied to any env/* yaml file like the `values-schema.yaml` does.

This will provide our users with better intelliSense.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

- Fix bugs for the `yaml` language server by Red Hat
- Create own language server for `yaml`

None of these alternatives make sense to me for obvious reasons.

- Keep `values-schema.yaml` 

I think we lose out on a lot of value by not providing users with a better experience when they set up their `otomi-values` repository. On the other hand, `yaml` is our language by choice. But by that logic we should also have `settings.yaml` in `.vscode`. I think (at least for me) it will also be nice to use the features offered by more feature-complete and mature solutions such as prettier which will also format the code.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Morriz** [comment]
I say lets wait for the outcome of the bug report you filed with redhat @svatwork. Can you post the link to that here?

**Comment by svatwork** [comment]
I can't reproduce the error right now, the current configuration seems to have solved it. You also walked me through the transformations of `values-schema.yaml` so I feel less lost now.

**Comment by Morriz** [comment]
But I was hoping that yaml would become at part with json functionality. Does the yaml variant now not fail to show usage for the json schema basic properties? You gave me a demo of that. Is that solved now then?

**Comment by svatwork** [comment]
Let me gather some evidence first, I'm keeping it in mind. There are still enough open [issues](https://github.com/redhat-developer/yaml-language-server/labels/bug). I wouldn't say that YAML is at part with JSON functionality, but I can work with it. I have usage for the JSON schema basic properties now, but not including all features in the JSON variant. 

It's just small stuff like that, I feel a little weird validating a YAML schema with a JSON schema, besides, all the documentation is in JSON. Then the YAML schema uses a JSON validator (ajv) to validate a YAML schema, and that will sometimes break things like multi-line sentences or insert random characters. 

But these are just things I've noticed, and I haven't collected enough evidence yet to make a strong case. Like I said, I just want to have a discussion about it, if it's not something that is bothering the rest of the devs then I might as well drop it.

**Comment by Morriz** [comment]
I am more interested in making the yaml validation more robust, that is why I keep hammering on fixing upstream. So where is the link to that issue with redhat?

**Comment by svatwork** [comment]
I haven't created it, let me gather some evidence and then I'll open one and post it here.
