### ISSUE TITLE
Upgrade tools to use new helmfile

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#250]
When this one is released: https://github.com/roboll/helmfile/pull/1618

we should upgrade tools to use that helmfile and add:

`disableValidationOnInstall: true`

to our helmfile defaults so that it is able to install crds and the chart in one go upon first install.

**Comment by mumoshu** [comment]
@Morriz FYI, v0.136.0 has been released for https://github.com/roboll/helmfile/pull/1618 😃

**Comment by Morriz** [comment]
Awesome. Thanks for reporting back. You are always so helpful!

**Comment by Morriz** [comment]
@rawc0der would you be so kind and integrate this new release in our tools image? You are probably upgrading your tools soon anyway, so I am assigning it to you.
