### ISSUE TITLE
yq error message when not installed locally

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#265]
**Describe the bug:**
yq@3 needs to be installed on the local machine. Since yq@4 is released, just installing yq will cause problems due to breaking changes from yq@3 to yq@4.

**To Reproduce**

1. Have no `yq` installed
    - ` . bin/aliases`
    - `oaz login`
    - Observe error message `yq: command not found`
2. Have `yq@4` installed
    - ` . bin/aliases`
    - `oaz login`
    - Observe error message `unknown command "r" for "yq"`

**Expected behavior:** 
Throw error when yq@3 is not installed or document the dependency on yq@3 or run yq@3 in container

**Comment by Morriz** [comment]
closing as this is packaged in container and we decided to run all calls with deps in container.

**Comment by Dunky13** [comment]
@Morriz  that means that all common.sh yq calls need to be rewritten to be ran in a docker container. Even for initialisation of otomi bridge on the local machine. Is that correct? If that's the case, it would make the codebase unnecessarily clunkier?
