### ISSUE TITLE
generate service account for workloads

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#275]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem

We now use SA "default" which gives access (albeit limited, see `values/k8s/k8s-raw.gotmpl`) to all resources in the team namespace.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

We should generate service accounts with RBAC to limit access to the workload dependencies only.

What are suspects for those deps:

- So far we only see configmaps, as secrets are handled by bank vaults.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

Implications:

- The console should ask the user for service dependencies so that we have the input we need for RBAC generation (and netpols, but that can be another PR).

**Comment by j-zimnowoda** [comment]
Having a dedicated SA per workload is also the requirement for authenticating at Vault. 
Thus this issue should have high priority.
