### ISSUE TITLE
Update otomi-tools' jq

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#282]
**Is your feature request related to a problem? Please describe.** 
CI of `otomi-core` fails when having `yq` and `jq` as shadow functions that execute through docker `otomi-tools`. 
Turns out that `otomi-tools`' jq version is 1.5 and has apparently issues with json piped to it.
jq in `otomi-tools` needs to be updated to 1.6

**Describe the solution you'd like** 
Update `otomi-tools` to use jq-1.6 instead of 1.5
In preliminary tests, it seems to resolve the CI issue, where piping the yq's shadow output to jq's shadow would fail.

**Comment by Morriz** [comment]
Can you not create issues for PRs that are not delivered to master yet? Just incorporate your findings there. Closing this.
