### ISSUE TITLE
otomi validate-templates does not always fail on error

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#284]
**Describe the bug:** (a clear and concise description of what the bug is)
I explored build logs from `otomi-core` and found out that bin/validate-templates.sh does not fail on error. 

**To Reproduce**
1. See logs https://github.com/redkubes/otomi-core/runs/1723535137?check_suite_focus=true
2. Observe lines:
```
bin/common.sh: line 11: CLOUD: unbound variable
316
tar (child): schemas/v-standalone.tar.gz: Cannot open: No such file or directory
317
tar (child): Error is not recoverable: exiting now
318
tar: Child returned status 2
319
tar: Error is not recoverable: exiting now
320
Validation Success
```

**Expected behaviour:** (a clear and concise description of what you expected to happen)
The build and tests always fail on any error.

**Comment by svatwork** [comment]
Yes, I've noticed this too. So it could be that some of the code we check in is not that predictable.

**Comment by rawc0der** [comment]
I found some of the concepts we are using too be flawed, as we are making very wrong assumptions.
For example:
 - we are using `set -e` and assigning `exitcode=0`. Initializing it with `0 is wrong. We should start running this kinds of programs with the assumption that it is `Failing` unless everything went fine, then set it to `0`/`Success`.
 - if something not related to the part of the script which sets `exitcode=0` fails, then the script exits with `0` making the build pass.
Come on guys.. I made a lot of changes that were not taken into account related to all sorts of issues like these. Now we have to revisit them again.

**Comment by Morriz** [comment]
This ONLY relates to CI unset. I rewrote this to collect failures IF CI=true, AND exit with 1 IF at least one error occured...was there regression?

**Comment by Morriz** [comment]
The trap function should of course ALWAYS exit with 1 if $? ne 0. Maybe that is not the case

**Comment by Morriz** [comment]
@j-zimnowoda can you next time please be precise in your bug report? This is about `otomi validate-templates`.

**Comment by Morriz** [comment]
I think this script is not correctly configured to guard against missing input. It should:
- only need ENV_DIR if no extra flag was given
- also need CLOUD & CLUSTER otherwise

But this script just keeps running if the pre-conditions are not met. @rawc0der can you fix that?

And then add this extra piece to the trap function condition:
```
[ $? -ne 0 ] && 
```

**Comment by j-zimnowoda** [comment]
Reopening as this bug is not fixed.

**Comment by Morriz** [comment]
fixed in upcoming merge with master

**Comment by j-zimnowoda** [comment]
Sorry, I have to reopen it, there are still bugs in this script:

```
Validating resources for cluster 'aws-demo'
355
WARN - knative-init/templates/all.yaml containing a CustomResourceDefinition (knativeeventings.operator.knative.dev) was not validated against a schema
356
WARN - knative-init/templates/all.yaml containing a CustomResourceDefinition (knativeservings.operator.knative.dev) was not validated against a schema
357
ERR  - kubeapps/templates/apprepositories.yaml: Failed initializing schema file:///tmp/otomi/kubernetes-json-schema/v1.17-standalone/apprepository-kubeapps-v1alpha1.json: properties must be of type object
358
Generating k8s v1.18 manifests for cluster 'azure-demo'
```


Refer to: https://github.com/redkubes/otomi-core/runs/1874200118

**Comment by Morriz** [comment]
fixed on master
