### ISSUE TITLE
Link wiki to otomi.io

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#285]
**Is your feature request related to a problem? Please describe.** 

I would like to share this demo as a repo but the official documentation isn't that visible. 

**Describe the solution you'd like** A clear and concise description of what you want to happen.

My preferred solution would be to insert this link in the "Wiki" button in this repository.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

It's in the README.md but it requires the reader to read the whole page. If you skim it then you will miss it.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by svatwork** [comment]
So I found a URL to otomi.io under "To get up and running with the platform please follow the online documentation for Otomi Container Platform. It lists all the prerequisites and tooling expected, so please read up before continuing here." but I still think it should be more visible than that.

**Comment by Morriz** [comment]
Can you fill in the template? I don't know what this is about...
```
Is your feature request related to a problem? Please describe. 
```

**Comment by Morriz** [comment]
Can you please be more precise about your proposed solution? If this is just a link in the wiki, then please add it and don't start a feature request.

**Comment by svatwork** [comment]
In the configuration of this repository I believe you can set the "wiki" tab above to reference otomi.io directly. I don't have the permissions for that.

**Comment by Morriz** [comment]
done

**Comment by svatwork** [comment]
Sorry about that, it used to be that it would immediately open another website. Or I'm just assuming this and my memory is failing me. I don't mind if you remove it now, because this might not be a big improvement.

**Comment by Morriz** [comment]
I did not find that option, but this is fine and can't do damage I think
