### ISSUE TITLE
Propagate helmfile parameters to otomi validate-templates 

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#290]
We want to limit `otomi validate-templates` to select charts for developing. 

Tasks:
- [ ]: Rewrite $1 part to instead take named parameter `--all` which implies to run the routine for all clusters (else the target cluster)
- [ ]: Add propagation from all helmfile parameters to templating commands (`hf template` -> `hf "$@" template`)

**Comment by Morriz** [comment]
@svatwork can this be pulled forward?

**Comment by svatwork** [comment]
I'm not certain what you mean, but if you mean focus on this, then yes, this is my priority.

**Comment by Morriz** [comment]
closing in favor of #330
