### ISSUE TITLE
Implement Gitea to hold otomi values

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#293]
# User story
As a user I would like to have a git repo for otomi values out of the box, so I don't have to bring my own.

# Definition Of Done
- [ ] Tasks are done
- [ ] (Unit) Tests are added to code
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`
- [ ] Specs and demo files have been updated to reflect code changes
- [ ] Documentation has been updated
- [ ] Functionality, code, and/or documentation has been peer reviewed
- [ ] Relevant team members have been notified

**Comment by svatwork** [comment]
Let's assign this to @Dunky13?

**Comment by Morriz** [comment]
good idea, as was already discussed :)

**Comment by svatwork** [comment]
I see then this moved into "progress"...

**Comment by Morriz** [comment]
IMO people should self assign when they start work. Communication about who does what should not be done via the "assignee" field, as that might change always.

**Comment by Morriz** [comment]
I don't want pre-assigning to hinder adoption by those who are available and ready to start on it.

**Comment by svatwork** [comment]
Yes that makes sense, sorry about that.

**Comment by Morriz** [comment]
No worries, no sorry's p

**Comment by Dunky13** [comment]
> As a user I would like to have a git repo for otomi values out of the box, so I don't have to bring my own.

Does this mean that we provide with a otomi-values template, that the use has to fill in themselves? Or a way for the user to configure the data, that is then inserted into the gitea o-v repo?
