### ISSUE TITLE
Unable to login to harbor registry

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#308]
**Is your feature request related to a problem?**
It happens quite often that, I am not able to login to harbor registry by using `User name` and `CLI secret` obtained from harbor UI.
```
$ docker login harbor.<cluster-domain> -u <User name> -p <CLI secret>
Error response from daemon: Get https://harbor.demo.eks.otomi.cloud/v2/: unauthorized: authentication required
```
The JWT obtained from Keycloak and forwarded, with each request, does not contain refresh_token. You can check it by visiting `httpbin.<cluster-domain>` service, perform request inspection and see content `Authorization` request header - the JWT.
From the harbor documentation we read:
> The CLI secret is associated with the OIDC ID token. Harbor will try to refresh the token, so the CLI secret will be valid after the ID token expires. However, if the OIDC Provider does not provide a refresh token or the refresh fails, the CLI secret becomes invalid.

**Describe the solution you'd like**
Provide refresh_token to JWT when login to harbor

**Describe alternatives you've considered**
Communicate to the Harbor community that making validity of `CLI secret` depending on validity of JWT may not be a good idea, as these are two separate authentication mechanisms. Each to them follows its own rules.
Waiting for response: https://github.com/goharbor/harbor/issues/14172

**Additional context** Add any other context or screenshots about the feature request here.
Workaround: a user needs to logout from otomi and login once again.

**Comment by Morriz** [comment]
@j-zimnowoda the title reveals a bug. Can you then please, please use the bug report template? I really like good input, this is confusing. Closing
