### ISSUE TITLE
Unable to login to harbor registry

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#316]
**Describe the bug:** (a clear and concise description of what the bug is)

It happens quite often that, I am not able to login to harbor registry by using `User name` and `CLI secret` obtained from harbor UI.

1. Go to harbor service in otomi
1. Login with OIDC
1. Go to User Profile (right top corner)
1. Copy `< User_Name>` and `<Client secret>`
1. Wait 60 seconds (until JWT expires)
1. Open you terminal
1. Try to login to registry and observe error
```
$ docker login harbor.<cluster-domain> -u < User_Name > -p <CLI secret>
Error response from daemon: Get https://harbor.demo.eks.otomi.cloud/v2/: unauthorized: authentication required
```

This issue has been reported by me at harbor repository: goharbor/harbor#14172

Workaround: a user needs to logout from otomi and login once again and then obtain `CLI secret` from harbor 

**Expected behavior:** (a clear and concise description of what you expected to happen)
A can always use CLI secret for obtaining access to image registry

**Comment by Morriz** [comment]
The otomi.io docs should describe this limitation, and a Task added to expose a refresh token in Keycloak. Then this issue can be closed.

**Comment by Morriz** [comment]
Docs updated and Task created: https://github.com/redkubes/otomi-tasks/issues/22

closing this
