### ISSUE TITLE
Facilitate teams with ExternalSecrets and Vault

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#317]
**Is your feature request related to a problem? 
Teams can define ExternalSecrets CR that fetches values from Vault service. 
The ExternalSecrets are cluster wise.

**Describe the solution you'd like** 
See discussion: https://github.com/redkubes/otomi-core/discussions/279

**Describe alternatives you've considered** 
See discussion: https://github.com/redkubes/otomi-core/discussions/279

**Comment by j-zimnowoda** [comment]
Outcomes from demo:
1) teams should only be able to deploy ExternalSecrets that points to a specific vault path 
2) the `dataFrom` property is not needed right now

Ad1) check possible solutions: ExternalSecrets Scoping access` vs `OPA policies`

**Comment by svatwork** [comment]
We updated the story template: https://github.com/redkubes/unassigned-issues/blob/master/.github/ISSUE_TEMPLATE/user-story.md.

I don't know if it is beneficial, it should be helpful for a developer. If it's not, I'm eager to hear your feedback. 

I'm a bit confused, because this looks like a feature request, but it's a story apparently.

**Comment by Morriz** [comment]
Yeah, can you fix that @j-zimnowoda ? Please use the story template and use it correctly, as it holds process checkpoints.

**Comment by j-zimnowoda** [comment]
Please, do it if you have time for that

**Comment by j-zimnowoda** [comment]
> We updated the story template: https://github.com/redkubes/unassigned-issues/blob/master/.github/ISSUE_TEMPLATE/user-story.md.
> 
> I don't know if it is beneficial, it should be helpful for a developer. If it's not, I'm eager to hear your feedback.
> 
> I'm a bit confused, because this looks like a feature request, but it's a story apparently.

You are confused by format but do you understand the content ?

**Comment by svatwork** [comment]
> You are confused by format but do you understand the content ?

That's correct.

**Comment by Morriz** [comment]
Yeah, we don't ask just because...it really holds an entire checklist that needs to be ticked off

**Comment by Morriz** [comment]
It is still not clear why this issue exists @j-zimnowoda ? What should be the outcome of this?

**Comment by j-zimnowoda** [comment]
The story defines the outcome
