### ISSUE TITLE
Prometheus rule reporting node NotReady is failing

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#319]
**Describe the bug:**

Alertmanager is not sending alerts when a node is unhealthy (marked NotReady). 

**To Reproduce**

1. Start a new cluster
2. Deploy otomi
3. Mark a node NotReady? How?
4. Observe: no alerts triggered

**Expected behavior:**

A prometheus rule to trigger an alert.

**Comment by rawc0der** [comment]
Hi,

So I marked a node NotReady on `eks.gk-test`, but I see the alert firing:

```
[FIRING:1] Notification for cluster "otomi/aws/gk-test"
Description: ip-192-168-13-210.eu-central-1.compute.internal has been unready for more than 15 minutes.
 Graph: :chart_with_upwards_trend: Runbook: :spiral_note_pad:
 Details:
  • alertname: KubeNodeNotReady
  • cluster: otomi/aws/gk-test
  • condition: Ready
  • endpoint: http
  • instance: 192.168.72.49:8080
  • job: kube-state-metrics
  • namespace: monitoring
  • node: ip-192-168-13-210.eu-central-1.compute.internal
  • pod: prometheus-operator-kube-state-metrics-5c44f58f6c-cmctr
  • prometheus: monitoring/po-prometheus
  • service: prometheus-operator-kube-state-metrics
  • severity: warning
  • status: true
```
https://apps.gk-test.eks.otomi.cloud/alertmanager/#/alerts?receiver=default.  (login with admin as oidc is not gonna work for this cluster).

I think the alert will not fire if prometheus/alertmanager pods were scheduled on the troubled node ... accounting for overcommitment, if the pods can't be rescheduled then, there's no way to trigger any alerts.
My guess is that alert is configured correctly, but the pods can't be scheduled if there's no cluster-autoscaler enabled.

**Comment by rawc0der** [comment]
P.S. for repeating this process you can do the following:
- ssh into a node using private certificate generated on cluster creation
- break kubelet configuration so it will fail on restart
- observe status NotReady on node
- observe alert if prometheus+alertmanager pods are running

**Comment by Morriz** [comment]
great observation...last year we introduced a higher priorityclass for otomi-core pods, and at that time I was convinced by Taco (who added it) that there should be no need for multiple priorityclasses. Maybe we should have multiple? and make sure prometheus-operator chart pods get highest?

Shouldn't lower prio pods get evicted to redeploy higher prio pods? I think it works like that. So then we should introduce another PriorityClass.

**Comment by Morriz** [comment]
closing this as it is assessed to be of type "kubernetes scaling problem" which sometimes occurs when scaling is not enabled or not working for some reason (limits reached etc).

**Comment by svatwork** [comment]
Is this related: https://github.com/SUSE/doc-caasp/issues/684?

**Comment by Morriz** [comment]
Please corroborate by trying the suggestion from the link
