### ISSUE TITLE
A user can define containerPort for Knative Service 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#322]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
A user that defines a Knative Service is not able to provide containerPort. Instead, a platform selects the default port `8080` for the application that is running in Pod. However, we cannot assume that each application listens on port 8080, because it is a choice of developer.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Allow user to define container port for Knative Service.

**Describe alternatives you've considered** 
n/a

**Additional context** 
https://knative.dev/docs/serving/spec/knative-api-specification-1.0/#containerport
https://github.com/knative/serving/blob/master/docs/runtime-contract.md#inbound-network-connectivity

**Comment by Morriz** [comment]
May I ask if this is a problem? If so, why is this surfacing now? Are our users always deploying containers on port 8080? I was under the impression that knative detects the exposed port automatically, and connects it to the outside overlay network on port 8080.
