### ISSUE TITLE
commenting out values leads to errors without failing the validation

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#332]
**Describe the bug:** (a clear and concise description of what the bug is)

When a user comments out certain property values, the template generation fails.

1. comment out everything after `azure:` in `settings.yaml`
2. `otomi validate-values` > see that it is passing
3. `otomi values | grep -B1 -A1 azure` > see that it generated empty values for `azure:`
4. `otomi deploy` > See error because values where expected

**Expected behavior:** (a clear and concise description of what you expected to happen)

Empty props should be caught by the validator and disallowed if that would lead to problems.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Comment by j-zimnowoda** [comment]
Thanks for reporting that issue.
I took a look at `values-schema.yaml` file from `otomi-core` repo and realised that azure object does not have required properties specified. I believe we need to inspect templates and conclude which fields are required and which are not.

**Comment by Morriz** [comment]
Yeah, good idea. We should also be more specific in our azure schema what those fields are for. I will create an issue for that.

**Comment by Dunky13** [comment]
@Morriz So this issue is only to make the azure values required? And another issue is for specifying the azure fields?

**Comment by Morriz** [comment]
No, one by one inspection is needed and thought about

**Comment by Morriz** [comment]
We should move the problematic `azure` prop and its related information to where it belongs. I suspect that info is now only used for `azureMonitor` so we might move it to a new `azureMonitor` root prop.

Please decide together for definitive agreement on this. Include me please!

**Comment by svatwork** [comment]
I would propose to make an inventory of these kinds of errors, there is a whole category of errors that should be caught by the validator but aren't. I know the following logical categories exist:

- Valid schema
- Invalid schema
  - Caught by the validator
    - Throws a warning but skips it
    - Throws an error and exits
    - Throws an error but doesn't exit
  - Not caught by the validator
    - Schema allows objects that shouldn't be allowed

**Comment by Morriz** [comment]
> I would propose to make an inventory of these kinds of errors, there is a whole category of errors that should be caught by the validator but aren't. I know the following logical categories exist:
> 
> * Valid schema
> * Invalid schema
>   
>   * Caught by the validator
>     
>     * Throws a warning but skips it
>     * Throws an error and exits
>     * Throws an error but doesn't exit
>   * Not caught by the validator
>     
>     * Schema allows objects that shouldn't be allowed

Why? That is the validators' terrain. We configure it and happily read it's error output.

**Comment by Morriz** [comment]
closing in favor of #490
