### ISSUE TITLE
Upgrade Gitea chart to 1.14 (once available)

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#359]
**Describe the bug:** (a clear and concise description of what the bug is)
Currently the chart ignores the `psp-allowed-users` policy since the init container and the running container of gitea both need root access.
This also means that we cannot set securityContext (yet).
Once Gitea 1.14 is released (shouldn't take long anymore - https://github.com/go-gitea/gitea/milestone/76) then version-tagged rootless images will become available. Currently only the `latest` release has an extra "rootless" release (https://hub.docker.com/r/gitea/gitea/tags)

**To Reproduce**
 - Try to run the current Gitea version without ignoring `psp-allowed-users` it will break.
 - Try to run the current Gitea version with a security context, it will break. (https://gitea.com/gitea/helm-chart/pulls/115)

**Expected behavior:** (a clear and concise description of what you expected to happen)
With Gitea 1.14-rootless it should be able to run with a security context & not allowing to run as root without breaking.
- We don't need to ignore `psp-allowed-users` policy
- We can set a security context

**Versions:** 
- Core: dev
- Gitea: 1.13.4

**Comment by Morriz** [comment]
This is not a bug. I am removing this label
