### ISSUE TITLE
Add BATS tests for shell scripts

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#367]
Task for story: https://github.com/redkubes/unassigned-issues/issues/170

**Comment by Dunky13** [comment]
The `retrieve-credentials.sh` script is mostly 3rd party commands, that (from what I understood) shouldn't be tested.
There is no logic in this script (except possibly a check if `.sops.yaml` exists) that should/could be tested

**Comment by svatwork** [comment]
Thanks for improving BATS.

I don't really understand this issue, where do you propose to add BATS tests for "shell scripts"?

**Comment by svatwork** [comment]
Oh... this is one of those issues under a Zenhub story? It's hard to tell from Github.com...

**Comment by Morriz** [comment]
@Dunky13 I do expect the description field of an issue to always be filled with the work that needs to be done. We want to avoid confusion as to what an issue entails.

**Comment by Dunky13** [comment]
There is no confusion as this issue is linked in zenhub as a task to a story.
Tasks are defined as one-line items - titles in this case. Adding a description is duplicate work and adds overhead that is unnecessary.

**Comment by Morriz** [comment]
Well, then I am almost sure that it can just be a checkbox in the original story, and not created separately. If it involves delivery of a piece of work that is beneficial on its own, the whole world now only sees an issue with a title. Meaningless. We should avoid creating issues without contained meaning.
