### ISSUE TITLE
Otomi does not automatically pull latest version of `otomi-core:master` & `otomi-core:latest` image

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#370]
**Describe the bug:** (a clear and concise description of what the bug is)
When Otomi values repo defines `otomi-core:master` docker image and an older version of this image already exists locally, it will use the old version instead of pulling the newest version of `otomi-core:master` (also applies to `otomi-core:latest`)

**To Reproduce**
1. Download old version of `otomi-core` and tag it as `otomi-core:master`
2. Run `otomi deploy`
3. Observe old version being deployed.

**Expected behavior:** (a clear and concise description of what you expected to happen)
When using `otomi-core:master` or `otomi-core:latest`, the command `otomi deploy` will pull the latest version of this image.
Does not apply when using versioned image, but otomi keeps `otomi-core:master` and `otomi-core:latest` image up-to-date.

**Versions:** (seen in console's `/settings`)

- Core Version: master

**Comment by Morriz** [comment]
This is inherent to docker, and adding that step incurs a performance impact.

The same goes for docker-compose. Even their own product does not do a pull every time. They leave that up to the dev to decide.

Closing this as a no-op. Tnx for the report. Maybe this will benefit somebody later...

**Comment by Dunky13** [comment]
Is the performance impact that high, that if we do a `docker pull` on only master & latest tag?
If should only download a couple of layers. And would be a nice Quality-of-programming, not having to worry if master/latest are actually bleeding-edge.
Any other tag could be ignored. Thus would be interesting for devs that want to try it. Once in production it would use a versioned tag, that is not constantly pulled.
Plus, if the tag is up to date the execution is ~1.5s

**Comment by svatwork** [comment]
> only master & latest tag?

I just want to add: be careful with latest (https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375).

**Comment by Morriz** [comment]
> Is the performance impact that high, that if we do a `docker pull` on only master & latest tag?
> If should only download a couple of layers. And would be a nice Quality-of-programming, not having to worry if master/latest are actually bleeding-edge.
> Any other tag could be ignored. Thus would be interesting for devs that want to try it. Once in production it would use a versioned tag, that is not constantly pulled.
> Plus, if the tag is up to date the execution is ~1.5s

I just think that adds too much overhead for something that needs to be pulled only when an image is expected to be new

**Comment by Dunky13** [comment]
Master & latest (as the tag implies) should always be new, right? 
It does affect devs only, I think. But "knowing" about it, isn't a given - otherwise Bart wouldn't get the issue of old images?

**Comment by Morriz** [comment]
It is just a matter of learning to work with docker I guess.

**Comment by bartboshuizen** [comment]
Not really about docker, more about `otomi deploy`. Once you realise it won't update the `latest` or `master` images it's fine. However, I do believe more people starting with Otomi might run into this. Hence, the suggestion to, at the very least, log a warning when using `latest` or `master`  image that already exists locally.

That being said, let's leave it at that if you don't consider it to be useful.

**Comment by Morriz** [comment]
This is not a valid use case as people will not use "latest" in their cluster, which is not allowed by the policies.

"master" is used only by devs and as such every dev understands how to use docker.

**Comment by Morriz** [comment]
> at the very least, log a warning when using `latest` or `master` image that already exists locally.

We will not go windows style on users and show them a stupid message every time. This problem is inherent to docker. It is not smart to try to fix third party tools outside of those tools. I suggest you join those tools repos and learn why things exist the way they do. You can always ask why even docker themselves don't "fix" this...

Can we please continue and let this on be?

**Comment by j-zimnowoda** [comment]
@Morriz 
As `dev` I often to forget to pull master and loose my time because of that. 

I also would like to point out that drone pipeline always pulls the image, therefor I would like to preserve consitency and have same behaviour in CLI.

Can we reopen this issue ?

**Comment by Morriz** [comment]
I said already that the performance hit is too large (

> @Morriz
> As `dev` I often to forget to pull master and loose my time because of that.
> 
> I also would like to point out that drone pipeline always pulls the image, therefor I would like to preserve consitency and have same behaviour in CLI.
> 
> Can we reopen this issue ?

No, as I don't see any use case. Why can't you?

As "dev" you actually use local code, so that is not the case.
Only when you deploy from a values repo could you theoretically run into this problem, but that should not be:
- clients don't get master
- we ONLY allow our own repos to run master, but we depend on drone to do deployments

**Comment by Morriz** [comment]
I just tested the performance hit, and it is negligible from the bootstrap perspective. We could indeed do a docker pull just after determining the image tag. Reopening.

**Comment by svatwork** [comment]
> @Morriz reopened this 9 days ago

I thought #382 closed this?
