### ISSUE TITLE
Running specific bats will run all as well

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#371]
**Describe the bug:** (a clear and concise description of what the bug is)
When wanting to run a single bats file, it will run that one first,  and then run all other tests as well.

**To Reproduce**
run `otomi bats bin/tests/otomi.bats` for example - or any other test. It will run that test, and then run all defined tests as well

**Expected behavior:** (a clear and concise description of what you expected to happen)
Run only the supplied test. 
This can be achieved to modify `bin/otomi` the `execute` function, `bats` command.
From `drun bats -T "$@" bin/tests`, to `drun bats -T "$@"` but this won't run all tests. Which it should do as well.
Maybe implement an if-statement that checks if the number of arguments passed along to $@ is <not-empty> run only $@ otherwise run `bin/tests`

**Comment by svatwork** [comment]
Filter still works... `otomi bats -f $string_in_test_header`

**Comment by Morriz** [comment]
@svatwork does your observation mean this is a no-op? Then please close this with the correct label ("invalid" in this case).

**Comment by svatwork** [comment]
Yes, I guess it is. Without filter the default behaviour is to run all tests, and `-f` supports the use case to run specific tests.

**Comment by Morriz** [comment]
@svatwork this was reported as a bug and that label could have stayed next to the "invalid" label to reflect how we see this bug.

We don't have to remove labels unless we use those to indicate the stage of the process, such as "help wanted" .
