### ISSUE TITLE
BATS uses evironment variables from shell

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#372]
**Describe the bug:** (a clear and concise description of what the bug is)
When running the bats test, it takes some environment variables set in shell, instead of the variables set in the script.

**To Reproduce**
When running any function that calls/uses helm(file), it seems that helmfile takes the environment variables set in the terminal, and not in the script.

It seems to fail when running the bats test `otomi x bin/retrieve-credentials.sh`
This command runs `bin/retrieve-credentials.sh` as a docker container.
During the test, a setup function is called to create a temporary directory, and sets this (in script) to the ENV_DIR
`export ENV_DIR=$test_temp_dir`

Echoing `$ENV_DIR` shows the path to the temporary directory. But in the trace, you see it points to `/Users/marc/Desktop/otomi-core/env/env/charts/secrets.harbor.yaml` 
Which is a) incorrect folder and b) not the temporary directory.

**Expected behavior:** (a clear and concise description of what you expected to happen)
That helm(file) use the ENV_DIR set by the script, when the execution path is within that script.
And parsing files where
`$ENV_DIR/env/charts/secrets.harbor.yaml` == `$test_temp_dir/env/charts/secrets.harbor.yaml`

**Additional context:** (add any other context about the problem here)
```sh
> otomi x bin/retrieve-credentials.sh
command "/home/app/tools/helm" exited with non-zero status:

PATH:
  /home/app/tools/helm

ARGS:
  0: helm (4 bytes)
  1: secrets (7 bytes)
  2: dec (3 bytes)
  3: /Users/marc/Desktop/otomi-core/env/env/charts/secrets.harbor.yaml (65 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Failed to get the data key required to decrypt the SOPS file.
  Group 0: FAILED
    projects/otomi-cloud/locations/europe-west4/keyRings/otomi/cryptoKeys/vault: FAILED
      - | Cannot create GCP KMS service: google: could not find
        | default credentials. See
        | https://developers.google.com/accounts/docs/application-default-credentials
        | for more information.
  Recovery failed because no master key was able to decrypt the file. In
  order for SOPS to recover the file, at least one key has to be successful,
  but none were.
  Error: plugin "secrets" exited with error

COMBINED OUTPUT:
  Decrypting /Users/marc/Desktop/otomi-core/env/env/charts/secrets.harbor.yaml
  Failed to get the data key required to decrypt the SOPS file.
  Group 0: FAILED
    projects/otomi-cloud/locations/europe-west4/keyRings/otomi/cryptoKeys/vault: FAILED
      - | Cannot create GCP KMS service: google: could not find
        | default credentials. See
        | https://developers.google.com/accounts/docs/application-default-credentials
        | for more information.
  Recovery failed because no master key was able to decrypt the file. In
  order for SOPS to recover the file, at least one key has to be successful,
  but none were.
  Error: plugin "secrets" exited with error
...
```

**Comment by Morriz** [comment]
@Dunky13 can you please rewrite your bug finding? It seems you are already writing solutions, but now it is not clear what the real bug is?

**Comment by Morriz** [comment]
Also, I think you are mistakenly reporting that $ENV_DIR would point to a file? Can you reproduce the command that shows me this?

**Comment by Morriz** [comment]
Also, can you NOT modify environment variables, but instead create your own variable names? (Possibly giving them the value of an ENV var as default.)

**Comment by Morriz** [comment]
I am closing this as I am 99% sure that this is a misunderstanding. I can explain better if you call me ;)
