### ISSUE TITLE
amazon env vars missing

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#380]
**Describe the bug:** (a clear and concise description of what the bug is)

when choosing to use awskms I don't see the needed env vars injected into drun:

```
AWS_DEFAULT_REGION
AWS_REGION
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```

In the current setup these are needed for sops.

Next to that I see `AWS_DEFAULT_REGION ` and `AWS_REGION` are also missing from vault operator.

**Comment by Morriz** [comment]
As this was a bit sloppy work, I am now wondering what else is missing from vault operator?

**Comment by mojtabaimani** [comment]
The region var is already there in config part of vault operator.
I will add other vars for aws to drun env.
