### ISSUE TITLE
otomi cli calls run twice

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#383]
**Describe the bug:** (a clear and concise description of what the bug is)

When running otomi cli calls they seem to get called twice. When running the following I see diff output twice:

`DEBUG=1 otomi diff -l name=loki`

**Comment by svatwork** [comment]
> DEBUG=1 otomi diff -l name=loki

Looks like `DEBUG`s meaning in the context of `bin/otomi` has changed to TRACE.

**Comment by Dunky13** [comment]
I checked out the master branch, and pulled the latest code. 
For testing purposes, I changed the Gitea version number from `1.13.4` to `1.13.6` 
Then I both: `DEBUG=1 otomi diff -l name=gitea` and `TRACE=1 otomi diff -l name=gitea`

In both cases the output was the same and I did not find the code running, or seeming to run twice.

If this is still a bug, that I am not aware of, please amend the description, so it can be more easily reproduced. As for now it seems this issue does no longer exist in `master`

**Comment by Morriz** [comment]
closing then...tnx
