### ISSUE TITLE
Loki time range incorrect

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#389]
**Describe the bug** A clear and concise description of what the bug is.

Loki does not show the time range in the graph.

**To Reproduce** Steps to reproduce the behavior.

Select time range with selector and observe the graph window time range.

**Expected behavior** A clear and concise description of what you expected to happen.

Graph to represent the selected time range.

**Additional context** Add any other context about the problem here.

This might be related to the other loki issue: [not showing logs](#171)

Another similar report: https://github.com/grafana/grafana/issues/26808

**Comment by svatwork** [comment]
> Another similar report: https://github.com/grafana/grafana/issues/26808

I think this is irrelevant, considering it looks like the problem here is that the time range is only limited to 3 hours, while I assume from your description we don't see any time range?

**Comment by Morriz** [comment]
Seems to be due to the limitation to manually have to provide a line limit (default 1000, max 500 in our setup). I added an issue with grafana here: https://github.com/grafana/grafana/issues/32791

**Comment by Morriz** [comment]
closing as new loki has better UI
