### ISSUE TITLE
Unable to deploy otomi without manual intervention

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#393]
**Describe the bug:** 
Unable to deploy otomi on brand new cluster.

**To Reproduce**

1. create a new cluster
2. call `otomi deploy` from you shell
3. Observe that deployments stucks
4. Observer that istiod k8s deployment is not able to schedule Pod `k -n istio-system describe deploy istiod`
5.
**Expected behavior:** 

It is enough to call once `otomi deploy`. No manual intervention needed.

**Additional context:** 
The workaround is to remove the `istio-injection` label from `istio-system`, so the istiod can deploy without istio sidecar.
```
k label ns istio-system istio-injection-
```
I really do not understand why this label is there in the first place. What was the intention?

**Comment by Morriz** [comment]
fixed

**Comment by j-zimnowoda** [comment]
thanks
