### ISSUE TITLE
ERROR: `getopt --test` failed in this environment.

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#419]
**Describe the bug:** (a clear and concise description of what the bug is)

`otomi bootstrap`  command in MacOS produce this error:
ERROR: `getopt --test` failed in this environment.

 Because of the difference between getopt command in macos and linux. 
You can avoid this error by installing the gnu-getopt and then 
`export PATH="/usr/local/Cellar/gnu-getopt/1.1.6/bin":$PATH` 

**To Reproduce**
Run otomi command in macOS.

**Comment by svatwork** [comment]
Yes, this is the expected behaviour. It should throw to let the user know whether the correct `getopt` is installed... So this is not a bug.
