### ISSUE TITLE
teams don't get alerts from failing pods in their namespace

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#432]
**Describe the bug:** (a clear and concise description of what the bug is)

teams don't get alerts from failing pods in their namespace

**To Reproduce**

1. Go to https://otomi.dev.eks.otomi.cloud
2. Deploy a new knative service based on a container that will fail startup (CrashloopBackOff)
3. Go to alertmanager team app and observe no alerts are reported (https://apps.team-otomi.dev.eks.otomi.cloud/alertmanager/)

**Expected behavior:** (a clear and concise description of what you expected to happen)

Alerts to fire for issues related to team workloads

**Additional context:** (add any other context about the problem here)

No targets are added to prometheus, so that is where it goes wrong in the first place.

**Comment by j-zimnowoda** [comment]
For failing image you can use `busybox` with the following command:
```
sleep 1; exit 1
```

**Comment by svatwork** [comment]
We discovered that `$v.serviceMonitor` for various services wasn't set properly, but that is not the original issue's problem.
