### ISSUE TITLE
Root Dockerfile could copy only necessary binaries from tools Docker

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#463]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

Our root Dockerfile uses a tools image (`tools/Dockerfile`) as a base layer. It seems to me we only need to copy over the binaries. That could save some space.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

`COPY --from=tools` everything instead of `FROM tools`, e.g. put all binaries in /usr/bin and the root Dockerfile will `COPY --from=tools /usr/bin /usr/bin`.

**Comment by Dunky13** [comment]
That is not necessarily true as the base image of tools plays an important role. Not every distribution works well with all binaries. I know alpine doesn't support everything Ubuntu does.

I do agree we should investigate optimizing our docker images.

**Comment by svatwork** [comment]
Yes, but that is not an issue, as you can just use the base image of either alpine or Ubuntu for pulling in the binaries.

**Comment by Morriz** [comment]
I suggest we deliver the tools/Dockerfile with a multi stage build, the last one cherrypicking the binaries

**Comment by Dunky13** [comment]
Also using experimental `--squash` flag, I managed to reduce the tools image by 500MB from 1.76GB to 1.15GB

**Comment by Morriz** [comment]
please create a PR if you think it is ready @Dunky13 ;)

**Comment by Dunky13** [comment]
I'm not working on that rn. Working on fixing bugs in the new CLI. I didn't spend time yet to optimize/move over binaries in the dockerfile.
