### ISSUE TITLE
AlertManager errors when values are not defined

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#472]
**Describe the bug:** (a clear and concise description of what the bug is)
Starting a fresh cluster with minimal values, and nothing defined for alerts, then alertmanager is started and throws an error shared in the comment below

**To Reproduce**
1. Start a fresh cluster with minimal values and don't define values for alerts.
2. Observe alertmanager crashing

**Expected behavior:** (a clear and concise description of what you expected to happen)
When no values are defined for alertmanager (prometheus) it is not started, and thus no errors occur.

**Comment by svatwork** [comment]
I see you use story syntax for a bug ("As a user..."), that is not necessary and can be a bit confusing. We only use that (imo weird sentence) for a story to indicate a business value as a specific stakeholder, here it is already clear what we need to solve (we don't need to translate a business requirement into a functional requirement).

**Comment by svatwork** [comment]
> Start a fresh cluster with minimal values and no values for alerts.

Could you elaborate on this, this confuses me a bit. Like where/how did you start a fresh cluster, did you only deploy AlertManager, did you deploy anything else, etc. It is useful to isolate the problem so other people can reproduce it.

**Comment by Dunky13** [comment]
Linked to this issue: https://github.com/redkubes/otomi-core/issues/471

```
level=info ts=2021-07-18T11:35:03.013Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.2, branch=HEAD, revision=44f8adc06af5101ad64bd8b9c8b18273f2922051)"
level=info ts=2021-07-18T11:35:03.013Z caller=main.go:222 build_context="(go=go1.16.4, user=root@b595c7f32520, date=20210602-07:50:37)"
level=warn ts=2021-07-18T11:35:03.254Z caller=cluster.go:251 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-po-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-po-alertmanager-0.alertmanager-operated.monitoring.svc on 10.0.0.10:53: no such host\n\n"
level=info ts=2021-07-18T11:35:03.254Z caller=cluster.go:253 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2021-07-18T11:35:03.254Z caller=main.go:312 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-po-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-po-alertmanager-0.alertmanager-operated.monitoring.svc on 10.0.0.10:53: no such host\n\n"
level=info ts=2021-07-18T11:35:03.254Z caller=cluster.go:671 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2021-07-18T11:35:03.304Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2021-07-18T11:35:03.305Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="unsupported scheme "" for URL"
level=info ts=2021-07-18T11:35:03.305Z caller=cluster.go:680 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=51.364921ms
```

Second to last line: `err="unsupported scheme "" for URL"`

**Comment by Dunky13** [comment]
> Could you elaborate on this, this confuses me a bit. Like where/how did you start a fresh cluster, did you only deploy AlertManager, did you deploy anything else, etc. It is useful to isolate the problem so other people can reproduce it.

@mojtabaimani and I started a fresh cluster using his chart installer. We used minimal values necessary to successfully start the cluster/stack. Except for setting up alerts. Then this error pops up.

**Comment by Morriz** [comment]
So did you fix the schema to align `charts.alertmanager.enabled` with the requirement of `alerts`?

**Comment by Dunky13** [comment]
> So did any of you fix the schema to align `charts.alertmanager.enabled` with the requirement of `alerts`?
> @mojtabaimani @Dunky13 

No not yet. Will look at it tomorrow

**Comment by Morriz** [comment]
This has to be fixed before we can deliver the chart to the public of course
