### ISSUE TITLE
Unable to login with OpenID connect

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#483]
**Describe the bug:** 

**To Reproduce**

1. Deploy otomi with default settings
2. Go to gitea dashboard 
3. Click `OpenID login` button
4. Observe error 404 not found

**Expected behavior:** 
Can login by clicking OpenID button

**Comment by Morriz** [comment]
do we care in dev mode? I think this is not a problem

**Comment by j-zimnowoda** [comment]
I found differences between working and not working setup for gitea OpenID login
After a user clicks the OpenID login button a `GET 
https://gitea.34.147.87.213.nip.io/user/oauth2/otomi-idp`
In the response there is redirect URL:
Correct redirect
```
https://keycloak.34.147.87.213.nip.io/realms/otomi/protocol/openid-connect/auth?client_id=otomi&redirect_uri=https://gitea.34.147.87.213.nip.io/user/oauth2/otomi-idp/callback&response_type=code&scope=openid&state=cecc23da-fac7-4ed8-9272-117295e2a299
```
Incorrect redirect which cause HTTP 404
```
/user/oauth2/?client_id=otomi&redirect_uri=https://gitea.20.103.81.12.nip.io/user/oauth2/otomi-idp/callback&response_type=code&scope=openid&state=e7927f00-2f39-4c99-b29a-e74f38ce4e1d
```
Now we need to find it out why the configuration differs

**Comment by j-zimnowoda** [comment]
**Killing `gitea` Pod solves this issue.**

**Comment by j-zimnowoda** [comment]
Added info in post-install steps: https://otomi.io/docs/installation/post-install/
