### ISSUE TITLE
Untrusted certificate cause OIDC login problem in Vault

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#484]
**Describe the bug:** 

**To Reproduce**

1. Deploy otomi with staging certificate and Vault
2. Go to Vault dashboard and select OIDC login
3. Observe that after pressing Login button a user is not redirected to OIDC login page

**Expected behavior:** 
Can login by with OIDC

**Comment by Morriz** [comment]
probably due to staging certs not yet working with vault

**Comment by j-zimnowoda** [comment]
I tracked the issue and found that:
Problem:
with self signed certificates Vault is not configured by at all
Cause:
The vault-configurer claims about unknown CA
```
 Get \"https://keycloak.20.103.49.223.nip.io/realms/otomi/.well-known/openid-configuration\": x509: certificate signed by unknown authority"
```
Solution:
Mount root CA at vault-configurer Pod
The vaultConfigurer settings is done in vault-operator (values/vault-operator/vault-operator-raw.gotmpl)

**Comment by j-zimnowoda** [comment]
Started coding in `vault-fix` branch

**Comment by j-zimnowoda** [comment]
https://github.com/banzaicloud/bank-vaults/issues/1468

**Comment by j-zimnowoda** [comment]
solved
