### ISSUE TITLE
Gitea init script randomly does not push values to remote origin

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#485]
**Describe the bug:** 

During initial install the `gitea-push.sh` script sometimes does not push values to the Gitea repo.

**To Reproduce**

1. Install otomi
2. Observe that 
3. Observe that Gitea is not ready  

**Expected behavior:** (a clear and concise description of what you expected to happen)

Gitea script waits until Gitea service is ready.

**Comment by Dunky13** [comment]
Will fix in new CLI
