### ISSUE TITLE
After initial installation vault-external-secrets is crashing

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#486]
**Describe the bug:** (a clear and concise description of what the bug is)

 I see the vault-external-secrets pod crashing during the first install. When that happens, you need to kill it and also kill Grafana. Otherwise, Grafana and Loki are not available; I also noticed the install of Harbor runs into issues because of this.

**To Reproduce**

1. Deploy otomi from scratch
2. observe  vault-external-secrets crashing

**Comment by Morriz** [comment]
probably due to staging certs not yet working with vault

**Comment by Morriz** [comment]
never see this happening anymore, closing
