### ISSUE TITLE
Older versions of otomi chart can not be installed. 

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#492]
**Describe the bug:** 
The older versions of chart can not be installed. 

**To Reproduce**
Current chart version is 0.1.6 and if you run `helm install otomi otomi/otomi` or `helm install otomi otomi/otomi --version 0.1.6` then you can install the latest version of the chart which is 0.1.6. But we have an older version which is 0.1.2 and if you try to install that by running `helm install otomi otomi/otomi --version 0.1.2` you will see the error message: ``Error: failed to download "otomi/otomi" at version "0.1.2" (hint: running `helm repo update` may help)`` and also `helm repo update` will not help as well.

**Comment by svatwork** [comment]
I don't know much about it, but I expect that if you create a new release the most recent Chart gets replaced by the new one.

Is it a bug though?

**Comment by Morriz** [comment]
why would this this problematic?

**Comment by svatwork** [comment]
Because it will not make a nice list of releases on the static html generated by the `gh-pages` branch.
