### ISSUE TITLE
Drone pipeline is not triggered by changes in git repository 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#499]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Install otomi from chart
2. After successful installation go to otomi dashboard and make a change in any configuration
3. Deploy changes
4. Observe that drone pipeline is not triggered
5. Observe that `.drone.yml` is not generated

**Expected behavior:** (a clear and concise description of what you expected to happen)

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)

**Comment by j-zimnowoda** [comment]
The solution comes with the new CLI

**Comment by Dunky13** [comment]
Drone generation is fixed in the new CLI. Using bootstrap is should generate automagically now.
