### ISSUE TITLE
Helm chart repository previous versions

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#500]
**Describe the bug:** 
When making a new otomi chart release, it will override the index.yaml file of the chart repository and doesn't keep the previous versions. But it should just append the new version to the current index.yaml.
 
**To Reproduce**

1. change the version of the chart in chart/otomi/chart.yaml and push to master 
2. go to branch: gh-pages and look at index.yaml file. You will see only the latest release and not the older ones. 

**Expected behavior:** (a clear and concise description of what you expected to happen)
It should update the index.yaml file with the new release and not creating and replacing a new file.

**Comment by mojtabaimani** [comment]
related link: https://helm.sh/docs/howto/chart_repository_sync_example/#generate-an-updated-indexyaml

**Comment by svatwork** [comment]
https://github.com/helm/chart-releaser/issues/122

**Comment by dominikatrela** [comment]
@mojtabaimani please create a story out of this and it in backlog

**Comment by Morriz** [comment]
@svatwork I removed your link to a chart releaser action issue, as that was unrelated (feature request to overwrite existing release, which should never happen imo).

**Comment by svatwork** [comment]
I thought we were using that action, and anyway, I sent a wrong issue, I actually meant this one: https://github.com/helm/chart-releaser-action/issues/70 (ie., chart releases get appended not overwritten). Or maybe I don't understand the problem correctly.

**Comment by Morriz** [comment]
> @mojtabaimani please create a story out of this and it in backlog

I don't see a story here, but do suggest to talk to the 3rd party software owner and check wether this will be, or is already implemented. After doing so the assignee of this issue should put this either "On hold" with a remark that we're waiting for feedback, or just put this issue "in progress" and configure it correctly.

@mojtabaimani please from now on always work this way. Please don't let 3rd party software quirks end up as an issue that has no next steps.

**Comment by j-zimnowoda** [comment]
fixed
