### ISSUE TITLE
the otomi destroy command does not work

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#513]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**
1. otomi destroy -vvv  
```
Checking for updates
Preparing docker environment variables
Checking if in dev environment
Pulling latest version of the docker image, please wait
master: Pulling from otomi/core
Digest: sha256:1c291305ac79aac2d2c575e0e9643213af50e3152ba6e564498fd7b201bf3abe
Status: Image is up to date for otomi/core:master
docker.io/otomi/core:master

 otomi:destroy:error helmfile-init.yaml: basePath=. +0ms
```
3. Observer that nothing is destroyed and command exit code is not zero

**Comment by Dunky13** [comment]
The reason things are not printed, even with multiple V's is because all helmfile commands are run without piping stderr. It shouldn't take lot of time to print to stderr to find what's wrong

**Comment by Morriz** [comment]
> The reason things are not printed, even with multiple V's is because all helmfile commands are run without piping stderr. It shouldn't take lot of time to print to stderr to find what's wrong

this is problematic @Dunky13. Can you fix that? Also, when ENV_DIR is not set, or the wrong command is given (typo), the cli returns without feedback. Can you fix that also?

**Comment by Dunky13** [comment]
> Also, when ENV_DIR is not set, or the wrong command is given (typo), the cli returns without feedback. Can you fix that also?
@Morriz is this a separate issue?
> this is problematic @Dunky13. Can you fix that?
Yes I can, but I'm starting up after a week off, trying to see what has changed.

**Comment by Morriz** [comment]
> > Also, when ENV_DIR is not set, or the wrong command is given (typo), the cli returns without feedback. Can you fix that also?
> 
> @Morriz is this a separate issue?
> 

yes...some commands don't give feedback but I thought that would be known by now...

**Comment by Morriz** [comment]
closing as fixed
