### ISSUE TITLE
The otomi CLI self update does not work

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#516]
**Describe the bug:**
The otomi CLI self update does not work.

**To Reproduce**

1. Set `otomi.version` to your feature branch
2. Runu Otomi Cli and answer `yes` to update otomi CLI
3. See error
```
Newer version is available, do you want to update (yes/No)? yes
Performing self-update...
Downloading latest version...Failed: Error while trying to wget new version!
File requested: https://raw.githubusercontent.com/redkubes/otomi-core/dockerfix/binzx/otomi
```

**Expected behavior:** 
Describe in which scenarios otomi CLI shall update and make sure code works according to use cases

**Comment by Morriz** [comment]
Why would that update url exist? I can see that it won't work when the url is generated with `https://raw.githubusercontent.com/redkubes/otomi-core/$IMAGE_TAG/binzx/otomi` and one is working in core in a feature branch

**Comment by j-zimnowoda** [comment]
duplicate in redkubes/unassigned-issues#276

**Comment by Morriz** [comment]
Can we please close the one that is incorrectly placed? We agreed to report bugs where they exist. This is the initial one correctly placed in the core repo.
