### ISSUE TITLE
envalid.ts contains bug that doesn't parse .secrets properly

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#517]
**Describe the bug:** (a clear and concise description of what the bug is)
if `ENV_DIR/.secrets` contains `export FOO=BAR`, then `src/common/envalid.ts` won't parse FOO=BAR, because of the export

**To Reproduce**

1. Create a .secrets file with exported variables
2. Print `env` in playground
3. Observe that FOO is not parsed

Alernative:
1. have ENV_DIR point to valid values
2. run `binzx/otomi lint` 
3. Observe templating issues with `requiredEnv: required env var GCLOUD_SERVICE_KEY`

**Expected behavior:** (a clear and concise description of what you expected to happen)
FOO being parsed

**Proposed solution:**
Environment variables from a file (like .secrets or .env) are reflected both in `process.env` as well as within the zx shell commands

**Comment by j-zimnowoda** [comment]
Thanks, for reporting.
This bug make also prevent you from performing `git push` as git hook triggers otomi lint as well.
