### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#518]
**Is your feature request related to a problem? Please describe.** 
Currently we do not unit test our CLI. We don't have a unit test framework selected.

**Describe the solution you'd like** 
Investigate which unit test framework works best for ES2021 combined with ESM

And implement initial unit tests. Let's get to 80+% :)

**Comment by dominikatrela** [comment]
@j-zimnowoda please let us know about your findings

**Comment by Morriz** [comment]
Still relevant and needed yes. Shall we create one story of the CLI unit tests? Let's do regular reviews before doing the bulk to avoid making tests that are not well designed

**Comment by j-zimnowoda** [comment]
Unit tests framework is already integrated.
Test can be executed by calling `npm run test:ts`
