### ISSUE TITLE
CLI: Decryption doesn't happen on apply anymore

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#525]
**Describe the bug:** 
Decrypt needs to run manually before running apply. This step should be implied when running apply.

This should also run in CI mode, the decider whether or not decrypt should run is whether or not a `.sops.yaml` file is present

**Use cases**
In the chart installation decrypt is ran manually before apply. This step should be unnecessary as it should be ran by apply implicitly

**Comment by Morriz** [comment]
closing as already fixed
