### ISSUE TITLE
CLI: Installing otomi fails in bootstrap phase

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#527]
**Describe the bug:** 
Bootstrap fails in several key locations, so CLI instal can not && will not work.

**To Reproduce**
1. Start a new cluster on eks.
2. create an empty ENV_DIR location to store the values in.
3. Run `otomi bootstrap`

Current results, as is:
It fails, since `bootstrap git` cannot get values
If I run `bootstrap values` first and then `bootstrap git` then it fails on the git as well, but I observe another issue with bootstrap values.
1. Bootstrap git still relies on values being filled in.
2. Bootstrap values should, but does NOT, generate SOPS file, because it requires `ENV_DIR/env/settings.yaml` to be filled, which it isn't since it has just been bootstrapped.

**Expected behavior:** (a clear and concise description of what you expected to happen)
Bootstrapped values and not failing bootstrap command

**Possible solutions:**
- When running in CLI (interactive mode), then ask the user to pre-fill some values through asking some questions. These pre-filled values can then be used further on during bootstrap. In non-interactive mode (chart,ci,testing,etc) we skip these questions as we can assume some form of values being present

**Comment by Dunky13** [comment]
Questions that can be asked:
- Do you want to store the values on the cluster?
  - Yes: Set charts.gitea.yaml enabled=true
  - No: Ask for git repo, username, password, email
- Do you want to encrypt the secrets?
  - Yes: Select KMS provider (aws,google,azure,vault)
  -  No: Do nothing
- Cluster related questions
  - provider
  - region
  - name
  - domainSuffix
  - apiServer

**Comment by Morriz** [comment]
Indeed it's a good idea to get the minimal input for the CLI as well (chart does the same) with a wizard.
You have to make sure to collect all of the minimal input then. (What you presented in the below list i not complete). 

Please see below for some feedback on phrasing:

> On 23 Aug 2021, at 09:30, Marc Went ***@***.***> wrote:
> 
> 
> Questions that can be asked:
> 
> Do you want to store the values on the cluster?
I would ask: Do you want otomi to store it's gitops values in-cluster at gitea.$domainSuffix/otomi/values? (If not we will ask access details for an external repo.)
> Yes: Set charts.gitea.yaml enabled=true
> No: Ask for git repo, username, password, email
> Do you want to encrypt the secrets?
Maybe change that to: "Please select your KMS provider for encryption. Select "none" to disable encryption. (We strongly suggest you only skip encryption for testing purposes.)"

And don't present a default value here to make this an explicit choice.
> Yes: Select KMS provider (aws,google,azure,vault)
> No: Do nothing
> Cluster related questions
> provider
> region
> name
> domainSuffix
> apiServer
Ask this stuff first to be used in the above harvesting
