### ISSUE TITLE
Job fails to connect to Keycloak 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#555]
**Describe the bug:** (a clear and concise description of what the bug is)

The job uses the fault tolerant fetch to ensure that there keycloak service is responsive.
We observe that the fetch is performed successfully and then the next HTTP request fails due to lack of DNS record.

**To Reproduce**

1. Install otomi from the very first time
2. Observe that job-keycloak fails 

**Expected behavior:** (a clear and concise description of what you expected to happen)
The fault tolerant fetch ensures that a given URL is available by check 3 consecutive successful HTTP responses 

job-keycloak-i Waiting until keycloak is accessible at https://keycloak.jeho.eks.otomi.cloud
job-keycloak-i .................................................................................................................................................................................................................................................................................................................................................................................................READY!
job-keycloak > otomi-tasks@0.2.9 tasks:keycloak /app
job-keycloak > node dist/tasks/keycloak/keycloak.js
job-keycloak (node:17) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
job-keycloak (Use `node --trace-warnings ...` to show where the warning was created)
job-keycloak request to https://keycloak.jeho.eks.otomi.cloud/ failed, reason: getaddrinfo ENOTFOUND keycloak.jeho.eks.otomi.cloud
job-keycloak request to https://keycloak.jeho.eks.otomi.cloud/ failed, reason: getaddrinfo ENOTFOUND keycloak.jeho.eks.otomi.cloud
job-keycloak request to https://keycloak.jeho.eks.otomi.cloud/ failed, reason: getaddrinfo ENOTFOUND keycloak.jeho.eks.otomi.cloud
job-keycloak request to https://keycloak.jeho.eks.otomi.cloud/ failed, reason: getaddrinfo ENOTFOUND keycloak.jeho.eks.otomi.cloud
job-keycloak Creating openid client scope
job-keycloak Updating openid client scope
job-keycloak Creating role otomi-admin
job-keycloak Creating role team-admin
job-keycloak Creating identity provider
job-keycloak Getting mappers
job-keycloak Creating mapper upn to email
job-keycloak Creating mapper username mapping
job-keycloak Creating mapper sub
job-keycloak Creating mapper otomi-admin group to role
job-keycloak Creating mapper team-admin group to role
job-keycloak Creating otomi client
job-keycloak creating client email claim
job-keycloak adding login theme
job-keycloak Success!
```

**Comment by Morriz** [comment]
this was actually an issue in the tasks repo @j-zimnowoda, but it is already fixed in latest master there
