### ISSUE TITLE
Can compose otomi with Unix stuff

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#565]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

I can't pipe otomi output, e.g. from `otomi template`. 

**Describe the solution you'd like** A clear and concise description of what you want to happen.

I can pipe, redirect, etc. E.g. part of my output from `otomi template -l name=cert-manager`:

```
 otomi:template:log         apiVersions:
  otomi:template:log           - "*"
  otomi:template:log         operations:
  otomi:template:log           - CREATE
  otomi:template:log           - UPDATE
  otomi:template:log         resources:
  otomi:template:log           - "*/*"
  otomi:template:log     admissionReviewVersions: ["v1", "v1beta1"]
  otomi:template:log     timeoutSeconds: 10
  otomi:template:log     failurePolicy: Fail
  otomi:template:log     sideEffects: None
  otomi:template:log     clientConfig:
  otomi:template:log       service:
  otomi:template:log         name: cert-manager-webhook
  otomi:template:log         namespace: "cert-manager"
  otomi:template:log         path: /validate +4ms
```

But when I try to grep e.g. "CREATE" (`otomi template -l name=cert-manager | grep "CREATE"` I don't receive output. 

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Dunky13** [comment]
Cannot recreate:
```
➜ binzx/otomi template -l name=cert-manager | grep "CREATE"
# It's not possible to grant CREATE permission on a single resourceName.
          - CREATE
          - CREATE
```

**Comment by svatwork** [comment]
Couldn't do it for some reason with an alias, non-issue.
