### ISSUE TITLE
otomi-status configmap is not created after chart installation. 

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#569]
**Describe the bug:** 
I installed the chart successfully but otomi-status configmap was not created after the chart installation. So, another chart installation could run inside the cluster on top of this one. 

According to the line 57 of src/cmd/apply.ts, we create a configmap after chart installation to prevent another chart installation on top of the first one. User should modify or destroy otomi by cli and otomi chart is just for the first installation. 

**To Reproduce**

Install the chart. Then you will not see otomi-status cm in otomi namespace. So you can install the chart again without destroying otomi.

**Comment by Dunky13** [comment]
It works in CLI apply - so need to investigate in chart install

**Comment by Morriz** [comment]
closing as fixed by making the chart also use `commitOnFirstRun`
