### ISSUE TITLE
wc command in binzx/otomi generate extra empty space in $count

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#571]
**Describe the bug:** 

When generating a container_name in binzx/otomi wc will produce extra empty space in some os and it causes errors 

it should be for example: 
`otomi-core-dev-container1`
but it generates: 
`otomi-core-dev-container 1`

**Comment by Morriz** [comment]
please either fix this with a proper bash replacement or update the code to say we require gnu tools:
```
brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep
```

**Comment by Morriz** [comment]
I would love to see these little bugs be fixed the moment they are understood to be a simple and quick fix ;)
