### ISSUE TITLE
Don't generate secrets again when chart installation job fails and restart. 

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#572]
**Describe the bug:**
when chart installation job fails at the middle, then the pod will restart and all secrets will be regenerated again and it makes problems for apps that has been already deployed in previous attempt.  

**To Reproduce**
install the chart and delete the chart before finishing the installation, then try to install the chart again and you will see the passwords are regenerated. 

**Expected behavior:** 
if the chart installation is failed before finish, don't regenerate passwords and use the previously generated ones.

**Comment by mojtabaimani** [comment]
Also we need to delete that when the chart is successfully installed.

**Comment by j-zimnowoda** [comment]
I made a flow diagram:
![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/f5e62254-e838-4cc2-b344-3bfda2f98e78)

**Comment by svatwork** [comment]
If a pod is not allowed to run more than one time, just turn it into a Job controller and done? 

(Maybe I make a too simple assumption here but it sounds needlessly complicated after reading this thread).

**Comment by j-zimnowoda** [comment]
@svatwork it is fine if a pod in job runs several times.
But if a user provides incorrect values and otomi deployment fails at some point we do not want to regenerate secrets for those apps that have already been deployed. Therefor we need a mechanism to prevent from redeploying the secrets

**Comment by j-zimnowoda** [comment]
Marc will investigate enabling unit test framework while I am switching to another task

**Comment by j-zimnowoda** [comment]
I wrote down test scenarios
```
Feature: Install otomi from helm chart
  Background: Clean kubernetes cluster
    Given:
      otomi job does not exists
      secret otomi-generated-passwords does not exist
      secret otomi-password does not exist 
      secret otomi-values does not exist 
  Scenario: Keep generated passwords
    When user deploys otomi chart
    Then otomi job is created
    When otomi job is completed
    Then secret otomi-generated-passwords is created
    And secret otomi-password is created
    And secret otomi-values is created
    And otomi ConfigMap deployment status is deployed
```

```
Feature: Reuse generated passwords
  Background: Otomi has been deployed on cluster and then destroyed with CLI
    Given:
      otomi job exists
      secret otomi-generated-passwords exists
      secret otomi-password exists
      secret otomi-values exists
      ConfigMap does not exists
  Scenario: Reuse generated passwords
    When user deploys otomi chart
    Then otomi job is created
    When otomi job is completed
    Then secret otomi-generated-passwords is reused
    And secret otomi-password is created
    And secret otomi-values is created
    ConfigMap otomi has status equal to deployed
```

**Comment by svatwork** [comment]
Do you also receive this output?

```
2021-10-05T08:44:04.729Z otomi:global:error Error:
    at commitOnFirstRun (file:///home/app/stack/dist/cmd/apply.js:37:36)
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/app/stack/node_modules/zx/index.mjs:68:22)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by Morriz** [comment]
what release is that? master?
