### ISSUE TITLE
chart/otomi default values.yaml are outdated. 

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#573]
**Describe the bug:** 
default values.yaml file in otomi chart are not correct. 

**Expected behavior:** 
The default values.yaml should conform with the values-schema.yaml

**Comment by Morriz** [comment]
Can you please add only the minimal values there now? Just ask Sander if you don't know what that is, but there should be a script that generates those, right? Or did that not materialize? Probably not, so manually then for now

**Comment by Morriz** [comment]
just updated in master
