### ISSUE TITLE
conflict in container name in otomi-core local debugging

### ISSUE THREAD

**Issue by mojtabaimani** [redkubes/otomi-core#578]
**Describe the bug:**
When you open otomi-core in remote-container for debugging, you can not run otomi cli in your local machine anymore and you will get this error message: 

```
docker: Error response from daemon: Conflict. The container name "/otomi-core-dev-container-1" is already in use by container "d3a6a2ecca6902241f5a9c082dff92144df1fe833fab19e13b94fb3a67d96925". You have to remove (or rename) that container to be able to reuse that name.
```

**To Reproduce**
open otomi-core in remote-container, then run otomi bootstrap command in your local computer.

**Comment by mojtabaimani** [comment]
I had to delete the container: otomi-core-dev-container-1 manually to be able to run otomi bootstrap in my computer

**Comment by Morriz** [comment]
Maybe you had a run that got cancelled and resulted in container not being removed?

This is not happening to me at all (I think docker nicely removes containers with `--rm`), so I would like to ask you to ask others if they suffer from the same.

If this is about commands being run in the docker container, can you `echo $IN_DOCKER` there? That should be set as it is in the Dockerfile, but if it is not, something is wrong and it will try to run docker in docker, which is accommodated but not designed for the cli

**Comment by Morriz** [comment]
I have not heard about this in a long time, so I deem this a non-issue. Closing
