### ISSUE TITLE
Calling otomi CLI without arguments should print usage message

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#582]
**Describe the bug:** 
Calling otomi CLI without arguments should print usage message
**To Reproduce**

1. In shell call: `otomi` 
2. See error:   otomi:global:error Not enough non-option arguments: got 0, need at least 1 +0ms

**Expected behavior:** 
To see command usage and exit with 1.

**Comment by Morriz** [comment]
more regression? what is going on? this was solved over a week ago...have branches not been delivered?
