### ISSUE TITLE
regression: invalid values due to fields now missing in schema

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#590]
**Describe the bug:** (a clear and concise description of what the bug is)

In the console, when submitting a service form after choosing to use an existing TLS secret we now get a `422: invalid values detected` error, due to the following fields missing now in `values-schema.yaml`. These were there before and should be put back:

```yaml
definitions:
  service:
    certArn
    certName
    hasCert
```

Please use the git log to check when those values existed and in what commit those got removed.
For up to date details please use the entries from the otomi-api repo's schema!

**Expected behavior:** (a clear and concise description of what you expected to happen)

Values created by api to be valid.

**Comment by Morriz** [comment]
This is a bug reported by our customer, so please give it prio @dominikatrela

**Comment by svatwork** [comment]
I think you are mistakenly assuming, I can't find any trace of this in our git history.

Let's make a task to put it in the schema, but I expect you take some responsibility for putting go templating variables in the schema.

**Comment by j-zimnowoda** [comment]
I understand that we should cross check `otomi-core/values-schema.yaml` against `otomi-api/openapi` schema. The difference shall be a guide about what is missing in `values-schema.yaml`

**Comment by Morriz** [comment]
> I think you are mistakenly assuming, I can't find any trace of this in our git history.
> 
> Let's make a task to put it in the schema, but I expect you take some responsibility for putting go templating variables in the schema.
> 
> Proof:
> 
> ```
> git grep hasCert $(git rev-list --all) | grep values-schema.yaml
> git grep certName $(git rev-list --all) | grep values-schema.yaml
> git grep hasCert $(git rev-list --all) | grep values-schema.yaml
> ```

indeed it seems these values were only living in code, and this was never caught...

**Comment by Morriz** [comment]
@Dunky13 I believe you were ready with coding and testing? Is this ready?
