### ISSUE TITLE
A user is able to get access to values repo at gitea

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#591]
**Describe the bug:**
A clear and concise description of what the bug is

**To Reproduce**

1. go to gitea in browser (eg https://gitea.dev.eks.otomi.cloud)
2. hit “Register” and fill in dummyvalues
3. Go to “explore”  (if you dont see the repo yet, then wait a few minutes)
4. see that you can access values repo

**Expected behavior:**
Random users cannot create accounts. We allow only login through OIDC 
The admin access is the exception from that rule.

**Comment by Dunky13** [comment]
`values/gitea/gitea.gotmpl` needs an update to:
`DISABLE_REGISTRATION: false` under [Service](https://docs.gitea.io/en-us/config-cheat-sheet/#service-service)
`ENABLE_OPENID_SIGNUP: true` under [openid](https://docs.gitea.io/en-us/config-cheat-sheet/#openid-openid)
