### ISSUE TITLE
CLI: `otomi destroy` should not print errors that are not errors

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#596]
**Is your feature request related to a problem? Please describe.** 
When running `otomi destroy` on an aborted/incomplete deploy it can throw errors as it cannot delete resources that don't exist:
```
➜ ./binzx/otomi destroy  
  otomi:destroy:log Uninstalling otomi... +0ms
  otomi:destroy:error error: the server doesn't have a resource type "kiali" +0ms
  otomi:destroy:error helmfile-init.yaml: basePath=. +26s
  otomi:destroy:error Error from server (Forbidden): error when deleting "/tmp/otomi/destroy-template.yaml": namespaces "default" is forbidden: this namespace may not be deleted
  otomi:destroy:error Error from server (Forbidden): error when deleting "/tmp/otomi/destroy-template.yaml": namespaces "kube-system" is forbidden: this namespace may not be deleted +9s
  otomi:destroy:error Error from server (NotFound): apiservices.apiregistration.k8s.io "v1.packages.operators.coreos.com" not found +2s
  otomi:destroy:log Uninstalled otomi! +38s
```

**Describe the solution you'd like** 
`otomi destroy` should not print errors, that are actually not errors. Such as: `the server doesn't have a resource type "kiali"` is not an error, since the deploy was aborted before this resource was installed, so removing it shouldn't happen.

Also, it shouldn't try to destroy the default & kube-system namespaces, and thus not throw an error.

Same goes for the other errors. Some shouldn't happen, or aren't an error.

```
> When I destroy an otomi cluster
     And I aborted the deployment before it was complete
  Then I don't want to see errors for things that weren't deployed yet
     And I don't want to see errors for things that cannot & shall not be removed
```

**Comment by Morriz** [comment]
We don't care about this as this is a script that is allowed to encounter errors like that to be able to thoroughly remove stuff and only serves devs.

We could add a line to the command help "(might show errors when resources don't exist)"

**Comment by Morriz** [comment]
@Dunky13 can you add that? I am closing this issue
