### ISSUE TITLE
Prometheus disks gets full with metrics data that is not rotated

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#601]
**Describe the bug:** (a clear and concise description of what the bug is)

Cannot see new metrics from prometheus after its disk gets full.

**To Reproduce**

1. Deploy otomi
2. Deploy two team and 3 services 
2. Wait 9 days 
1. observe that no new metrics are available in grafana
1. observe that prometheus PV got full 
1. observe error in prometheus pod See error

```
prometheus level=error ts=2021-09-25T19:56:44.503Z caller=scrape.go:1163 component="scrape manager" scrape_pool=monitoring/po-kubelet/2 target=https://192.168.76.18:10250/metrics/probes msg="Scrape commit failed" err="write to WAL: log samples: write /prometheus/wal/00000213: no space left on device"
```
**Expected behavior:** (a clear and concise description of what you expected to happen)

Prometheus to use `--storage.tsdb.retention.size` argument that matches PV size, so disk is protected against overflow. 

Disk size shall be calculated based on formula provided at: https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
```
needed_disk_space = retention_time_seconds * ingested_samples_per_second * bytes_per_sample
```
so the disk does not get full before first samples are removed by prometheus.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/febff9e9-73ef-4dc3-82eb-cada921e747e)

**Cluster(s):**

- Cloud: aws
- Cluster: jeho

**Comment by Morriz** [comment]
Seeing this report @j-zimnowoda, I think it belongs in the prometheus repo's issues. Can you post it there?

**Comment by Morriz** [comment]
@j-zimnowoda and maybe create a comment here with a recap of the findings there? (Assuming there are more reports about this and activity is there.)

**Comment by Morriz** [comment]
investigated, and duration is honored by the rotation mechanism, but it can't know how big the disk should be...closing as a configuration issue.

To avoid this: choose a big enough disk size (guesstimate). 100GB default should be enough for the installer

**Comment by Morriz** [comment]
since loki ootb has 1 day retention, I set it to `1d` here as well, with `5Gi` total disk size, and retentionSize: `4Gi` so that 1Gi is available for additional processes such as WAL.
