### ISSUE TITLE
otomi values merge/extract or import/export

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#614]
**Is your feature request related to a problem? Please describe.**
I would like to be able to "import"/"export" values from a single file to our values folder and vice versa.

**Describe the solution you'd like** 
Create a sub-command on `otomi values` that is either `merge/extract` or `import/export` to `merge/import` a single values yaml into the values folder and `extract/export` the values folder into a single file. This would make managing the values easier than it is right now.

**Comment by Morriz** [comment]
Can you describe use cases?

**Comment by Dunky13** [comment]
For development is makes it easier to have a single file that you can import over bootstrapped values. Having a single source of values, that you can quickly modify to test. We already have the code (for chart) to import that file, but this would extract it into a command for CLI as well.
The export usecase would be, in regards of development/testing, easy when you have a values repo (cloned, or not) to extract/export the values into a single file, to quickly make changes, destroy cluster, share the file with others who can spin up the cluster easily with the same values (since it can't be cloned after destroy for example)

**Comment by Morriz** [comment]
Like discussed in standup, we can already import with just `VALUES_INPUT=/some/values.yaml otomi bootstrap`.

Export I can see for sharing but we may already share a whole zipped env dir. We don't wish to store unencrypted values files in repos but encrypted env dirs are already online to share. 

Anyway, if we are gonna add features that make things only look nicer, then lets focus on the ones that matter most to devs, and put this on low prio for now.

**Comment by j-zimnowoda** [comment]
already done
