### ISSUE TITLE
The `NGINX Ingress controller` dashboard in Grafana does not show anything.

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#626]
**Describe the bug:** (a clear and concise description of what the bug is)

The `NGINX Ingress controller` dashboard in Grafana does not show anything.  
**To Reproduce**

1. Open Otomi Console in webbrowser
2. Go to OtomiApps -> Grafana -> Dashboards -> Manage
3. From Dashboard list select `NGINX Ingress controller`
4. Observe that there are not any metrics displayed 

**Expected behavior:** (a clear and concise description of what you expected to happen)
See screenshots
**Screenshots:** (if applicable, add screenshots to help explain your problem)
Current
![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/ee314d7a-49cb-4661-9d49-1289b623d469)

Expected:
![Pasted Graphic 4.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/d10be37f-ca06-459a-b90e-07a4be11d45a)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version 0.14.17

**Comment by staticvoid255** [comment]
Is this fixed? I am happy to take this if not.

**Comment by Morriz** [comment]
@j-zimnowoda importing the main NGINX dashboard which has id 9614 (and which is packaged into Otomi) manually also does not work, so this needs investigating.

**Comment by Morriz** [comment]
this will be fixed when the PR for this bug is landing: redkubes/otomi-core#820
