### ISSUE TITLE
integration test is flaky and times out most of the time

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#643]
I believe we agreed on giving workloads minimal settings for `resources.request`, so the kind installer is not allocating too many resources (it seemingly runs out of). However, I don't see them in the `tests/fixtures/kind` values.

So the first step to see if we can avoid this is to do that work, and configure the values.

**Comment by svatwork** [comment]
I put it  `tests/kind/charts/_resources.yaml`
