### ISSUE TITLE
Bootstrap overwrites previously generated secrets

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#670]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Introduce some settings so deployment cannot succeed
1. Deploy otomi from chart
1. Observe that second attempt to deploy otomi overwrite existing secrets 

**Expected behavior:** (a clear and concise description of what you expected to happen)
Bootstrap does not overwrite secrets

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)
- [attempt1](https://app.zenhub.com/files/200118806/b6db3a6e-d52d-4281-83a0-07c3a64fa0f9/download)

- [attempt2](https://app.zenhub.com/files/200118806/7c4ecdad-0ffe-40aa-b56a-47d665afb1b5/download)

**Comment by j-zimnowoda** [comment]
From the logs I see that bootstrap discovers existing passwords but does not take it into account while saving final values.

**Comment by Morriz** [comment]
I am currently adding a unit test for bootstrap

**Comment by j-zimnowoda** [comment]
I have observed that the issue is still there

**Comment by Morriz** [comment]
fixed in bootstrap PR after caught with new test setup.
