### ISSUE TITLE
Default keycloak password is not working

### ISSUE THREAD

**Issue by damianesteban** [redkubes/otomi-core#701]
**Describe the bug:** (a clear and concise description of what the bug is)

I am unable to login to Keycloak with the password in the install log.

**To Reproduce**

I looked in the logs, here is the content:

```
    #  To start using Otomi, first follow the post installation steps: https://otomi.io/docs/installation/post-install/
    #  The URL to access Otomi Console is: https://otomi.xxxxxxxx.nip.io
    #  The URL to access Keycloak is: https://keycloak.xxxxxxxx.nip.io
    #  When no external IDP was configured, please log into Keycloak first to create one or more users and add them either to the 'team-admin' or 'admin' group.
    #  The password of the Keycloak admin user is: xxxxxxxxx
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
I expect the password in the logs to work.

**Cluster(s):**

- Cloud: GCP
- Cluster: [e.g. demo]

**Comment by Morriz** [comment]
Hi, I think the docs are not clear enough on this perhaps, but you must log in with the keycloak url first and create a user there. You can recognize the url as it uses the "master" realm.

Afterwards you can log in with that user with the otomi url.

Can you check if that works?

**Comment by Morriz** [comment]
We added a first user during install to bypass this problem. The log output is updated to reflect that. Closing this issue.
