### ISSUE TITLE
Installation fails on prometheus step on k3s

### ISSUE THREAD

**Issue by BloodWorkXGaming** [redkubes/otomi-core#709]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Having a clean single node onprem k3s cluster (Version 1.21 and 1.20 both have the same) on ubuntu
2. setting up helm repo
3. `helm install -f otomi-values.yaml otomi otomi/otomi`

After a few steps, the installation fails without an error or anything. The logs of both jobs are attached:
[otomi-dsqvs.log](https://github.com/redkubes/otomi-core/files/7877610/otomi-dsqvs.log)
[otomi-shvxb.log](https://github.com/redkubes/otomi-core/files/7877611/otomi-shvxb.log)

**Expected behavior:** (a clear and concise description of what you expected to happen)
Install job finishing successfully.

**Screenshots:** (if applicable, add screenshots to help explain your problem)
![image](https://user-images.githubusercontent.com/8137062/149672527-15b64624-2199-4e16-aff9-29e61e3e9c49.png)

**Cluster(s):**

- Cloud: onprem
- Cluster: single node cluster

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.15.1]
- Console Version: k3s 1.21.8
- API version: not sure

**Desktop:** (if relevant)

- OS: Ubuntu
- Browser: -
- Version: 22

**Additional context:** (add any other context about the problem here)
There is no difference whether there is flannel or cilium installed as a CNI.

Thank you in advance for any help :)

**Comment by Morriz** [comment]
May I ask what your resource specs are for that single node? The docs do say you need at least 12 vCPU and 12 GiB memory: https://otomi.io/docs/installation/prerequisites

**Comment by BloodWorkXGaming** [comment]
It's a Ryzen 3700X 8core 16Thread CPU with 32 gb of RAM, so that should be enough.
Missed the part of the docs where it says at least 3 Nodes, maybe that's why?

**Comment by Morriz** [comment]
> It's a Ryzen 3700X 8core 16Thread CPU with 32 gb of RAM, so that should be enough.

Should be enough indeed. 

> Missed the part of the docs where it says at least 3 Nodes, maybe that's why?

That is not needed per se.

But the logs don't show anything. Can you check the k8s events and describe the workload when it gets stuck? It could be all kinds of things.

**Comment by BloodWorkXGaming** [comment]
First of all, thanks for the help :)

The last operation happening in the log has something to do with etcd, which is not present on k3s depdending on the configuration.
https://thenewstack.io/how-rancher-labs-k3s-makes-it-easy-to-run-kubernetes-at-the-edge/
`K3s replaced, etcd, with a lightweight database called SQLite, which is a proven database for embedded scenarios.`

Maybe that's why?

Pretty busy today, but will try to check whether it works on a single node microk8s or another distribution in the evening.

**Comment by srodenhuis** [comment]
Closing this issue. Otomi now supports Civo k3s and this issue has not occurred.
