### ISSUE TITLE
The  istio-proxy container is injected to knative activator pod after it gets destroyed

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#713]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Kill activator Pod in `knative-serving` namespace 
2. Observe that `activator` Pod gets an extra container.
```
knative-serving     activator-6fb68fff7b-24fp5     ●     2/2                0 Running              0      0         0         0          0          0 10.4.2.207      gke-otomi-gks-jeho-n-otomi-gks-jeho-n-b4ebb121-0sf5      25s         │
knative-serving     activator-6fb68fff7b-gdlh4     ●     1/1                0 Terminating          3     17         1         0         28          2 10.4.2.9        gke-otomi-gks-jeho-n-otomi-gks-jeho-n-b4ebb121-0sf5      4h29m       │
```

Note that neither `knative-serving` namespace not `activator` pod use `istio-injection: enabled` label, so perhaps istio have different means to decide where to inject sidecar.

**Comment by Morriz** [comment]
@j-zimnowoda can this be closed now?

**Comment by j-zimnowoda** [comment]
I did not have a chance to reproduce it. Let me do it on Tuesday next week

**Comment by j-zimnowoda** [comment]
cannot reproduce anymore
