### ISSUE TITLE
How does one sign up for Otomi's community slack channel?

### ISSUE THREAD

**Issue by rohitkothari** [redkubes/otomi-core#715]
**Describe the bug:** (a clear and concise description of what the bug is)
This is not really a bug with otomi-core, however I did not find a better place to ask this. I am new to Otomi and was looking to give it a try, however was running into problems getting Otomi successfully running in my EKS cluster or get a new cluster running by following [Otomi's quickstart guide](https://github.com/redkubes/quickstart/tree/main/aws). I found your community page and links to [Gitter](https://gitter.im/redkubes/community) and [Slack](https://join.slack.com/t/otomi/shared_invite/zt-vourf7og-de4CmvthgfJlsuDQHsK8yQ) for chat, however did not receive a response on Gitter and could not sign up on Slack via Google.

Is the Slack channel open for community where users discuss their problems/questions regarding Otomi? If so, how can I get access to Slack for the same?

**To Reproduce**

1. Go to [Community Portal](https://redkubes.com/community/)
2. Click on slack icon on top right corner besides 'Articles'
3. On the slack sign up page, click on "Continue with Google" to sign up (as you don't have a '@redkubes.com' email ID)
4. Follow Google authentication process and you should see the following error message (refer screenshot below):

```
The email address must match one of the domains listed below. Please try another email.
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
Sign up with Google is successful for users not having '@redkubes.com' email ID.

**Screenshots:** (if applicable, add screenshots to help explain your problem)
<img width="476" alt="Screen Shot 2022-01-25 at 11 36 45 AM" src="https://user-images.githubusercontent.com/5898479/151048986-e4d34f02-2491-419e-a7fa-4dee683f2b21.png">

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)

**Comment by diabhey** [comment]
Hi @rohitkothari:  Thank you for bringing this to our attention. We will look into it and get back to you asap.

**Comment by Morriz** [comment]
Somehow that link to Slack was posted by one of our content moderators, but we don't offer Slack as a community channel. We will remove the link asap.

**Comment by diabhey** [comment]
@rohitkothari: We have fixed our Slack channel. Feel free to reach out to us.

**Comment by TwoTwenty** [comment]
The slack link seems broken again.
