### ISSUE TITLE
Make kiali CR resources configurable

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#721]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem

The kiali instance created by the operator may require higher memory limits for clusters with bigger amount of nodes. Thus resource limits shall be configurable via values:
```yaml
cr:
  spec:
    deployment:
      resources: ...
```

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Enrich schema for Kiali-operator and allow to set resource limits.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Morriz** [comment]
I am not convinced about that. If it has not enough resources we should just increase them. The kiali instances themselves might need more or less, as those handle the work. I updated the title to be more specific.
