### ISSUE TITLE
Drone pipeline fails (only first try)

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#726]
**Describe the bug:** (a clear and concise description of what the bug is)
If we apply changes via Otomi UI, drone will fail the first time and when restarting immediately it will work.
This becomes an issue in case users deploy something and dont have access to drone logs and dont realise it failed while waiting.

Drone is failing (only the first try) with these logs on the first step, named 'clone':
```
Initialized empty Git repository in /home/app/stack/env/.git/
+ git fetch origin +refs/heads/main:
fatal: unable to access 'https://github.com/XXX/otomi-values-ont.git/': Could not resolve host: github.com
```

**To Reproduce**

1. Make sure that drone has not been used for a while (some hours  perhaps)
2. make a change in otomi UI and deploy
3. Check drone pipeline and notice it failed on the first step (this might take 2-3minutes)
4. Hit 'Retry' and see the pipeline works now.

**Expected behavior:** (a clear and concise description of what you expected to happen)
Pipeline to work without failing first try.

**Cluster(s):**
AKS 1.21.2
Otomi  v0.15.3

**Comment by Morriz** [comment]
This is new to me, and I can see two reasons for this:
- github is not reachable, but from what you describe that seems illogical
- that the runner pod wasn't able to do egress, which indicates that a potential istio sidecar is initialized (that needs like 10 seconds to set up egress), which should not happen for the `drone-pipelines` namespace. Has something been modified on that particular cluster? Can you eliminate that possibility @bartusz01 and @j-zimnowoda ?

**Comment by srodenhuis** [comment]
Seems to be a one time issue probably due to external factors that can not be reproduced and is not occurring regularly.
