### ISSUE TITLE
kiali blocked

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#737]
**Describe the bug:** (a clear and concise description of what the bug is)

output from kiali pod:
```
ERR Error fetching initial namespaces for populating the Kiali Cache. Details: Get "https://10.0.0.1:443/api/v1/namespaces": dial tcp 10.0.0.1:443: connect: connection refused
```

**Comment by j-zimnowoda** [comment]
I do not think that it is caused by network policies, as they do only restrict traffic to team namespaces.
If that was Azure with SLA then kube-api could be unavailable for movement thus connection refused.

**Comment by Morriz** [comment]
alright...closing

**Comment by Morriz** [comment]
Strange that this consistently plays up though. Every time the kiali pod starts this is now happening.
