### ISSUE TITLE
The host-mod chart fails to install certificate on EKS cluster

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#747]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Deploy otomi with custom-ca and harbor enabled
2. upload image to harbor at team project
3. in team create service that fetches container image from harbor
4. See errors

hostmod POD:
```
cat: /etc/pki/ca-trust/source/anchors/harbor.18.195.63.109.nip.io.crt: No such file or directory
Updating /etc/pki/ca-trust/source/anchors/harbor.18.195.63.109.nip.io.crt
Found docker setup!
Found containerd setup!
All mods READY!
Restarting containerd...
```

ksvc log:
```
Message:                     Revision "cypress-service-replica-00001" failed with message: Unable to fetch image "18.195.63.109.nip.io/team-cypress/nodejs-helloworld:master": failed to resolve image to digest: Get "https://18.195.63.109.nip.io/v2/": x509: certificate is valid for ingress.local, not 18.195.63.109.nip.io.                                    │
```
**Expected behavior:** (a clear and concise description of what you expected to happen)

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)

**Comment by Morriz** [comment]
Why is the title suggesting something wrong with host-mods when the error clearly shows it tries to pull an image from the wrong repo (`https://18.195.63.109.nip.io/v2/`)? Was the image configure wrongly perhaps?

**Comment by Morriz** [comment]
The host-mods script serves 3 scenario's:
1. docker only
2. containerd only
3. both
But AWS says it does not support containerd yet for k8s in 1.21: `The default runtime for 1.21 will still be Docker, and you can opt-in to containerd runtime by adding a --container-runtime containerd option to your user data.`
The docker setup is almost never failing so I think this is a config problem.
