### ISSUE TITLE
upgrade kured

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#748]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
Current Kured version contains a flag to remove locks after a while, in case e.g. node reboots are failing, which would otherwise result in and endless lock. This does not work as expected however , but does work in newer versions (where chart values: `configuration.annotationTtl` is also renamed to `configuration.lockTtl`). Furthermore, current Kured version is expected to work on k8s 1.1[789].x for maintaining a lock and draining nodes, which are older versions that are not supported anymore by K8s.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
upgrade Kured Chart

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by j-zimnowoda** [comment]
already merged
