### ISSUE TITLE
Uninstall deprecated helm release

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#758]
**Is your feature request related to a problem? Please describe.** 

Sometimes a helm release is moved to a different namespace or is renamed and moved to different helmfile. 
In order to provided a smooth otomi upgrade scenario there has to be a way to automate removal of deprecated deprecated releases.

E.g.: 
In release 0.16.1:
The `gatekeeper-operator` has been renamed to `gatekeeper` release and moved to from `default` to `gatekeeper-system namespace`. Therefor  `gatekeeper-operator needs to be removed before applying `gatekeeper` release to avoid collision of cluster wide resources.
 
**Describe the solution you'd like** A clear and concise description of what you want to happen.
Add helmfile that allows to uninstall charts.
**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by j-zimnowoda** [comment]
Logs from otomi apply
```
  otomi:cmd:apply:applyAll:log gatekeeper-operator      default         1               2022-04-13 14:16:56.598122605 +0000 UTC deployed        gatekeeper-v3.2.2       v3.2.2 +1s
  otomi:cmd:apply:applyAll:log release "gatekeeper-operator" uninstalled +12s
```

**Comment by Morriz** [comment]
Important note: destructing running apps is not migrating them and must be avoided if those have state.

So can you please update the title to reflect this? And suggest another solution? We can think about it together...

**Comment by j-zimnowoda** [comment]
Yes, that is correct. We need to create a document that clearly explain deprecation process.
