### ISSUE TITLE
The git repository for argocd are created even if argocd is not enabled

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#791]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Install otomi with default settings 
1. Activate drone 
1. Create a team and deploy changes
1. Wait until deployment pipeline finishes
1. Login to the gitea app and observe that there are repositories with `-argocd` postfix

**Expected behavior:** (a clear and concise description of what you expected to happen)
Argocd git repos are created if argocd is enabled.

- Core Version 0.16.3

**Comment by Morriz** [comment]
fixed in v0.16.9
