### ISSUE TITLE
prometheus-blackbox-exporter issue for team services

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#792]
**Describe the bug:** (a clear and concise description of what the bug is)
When checking a teams  prometheus targets `probe-services-<team>` I see the following error: 

`
Get "http://prometheus-blackbox-exporter.team-<team>:9115/probe?module=http_2xx&target=https%3A%2F%2F<url>": dial tcp: lookup prometheus-blackbox-exporter.<team-namespace> on 10.0.0.10:53: no such host
`
Otomi version: 0.16.2

**Comment by j-zimnowoda** [comment]
@Morriz could you review this issue? I am wondering if  `svc: prometheus-blackbox-exporter` defined in ` team-ns-{{ $teamId }}` helmfile refers to this issue?
