### ISSUE TITLE
The checkPolicies fails on gatekeeper install/upgrade 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#795]
**Describe the bug:** (a clear and concise description of what the bug is)

The `otomi check-policies` uses `conftest`, which  scans manifests from all namespaces.
By enabling `container-limits ` policy it is not possible to upgrade gatekeeper anymore.

**To Reproduce**

1. Enable container-limits policy
2. Upgrade gatekeeper (in console change Otomi version that contains the gatekeeper upgrade)
3. Observe that drone pipeline fails at `tests` step

**Expected behavior:** (a clear and concise description of what you expected to happen)
The gatekeeper upgrade Job contains required resource limits.

**Screenshots:** (if applicable, add screenshots to help explain your problem)
![image.png](https://images.zenhubusercontent.com/5e81a8d81dea46667ed31838/cc0302ad-f2ad-48af-92c9-6e6dc2cb6890)
**Versions:** (seen in console's `/settings`)

- Core Version 0.16.3

**Comment by Morriz** [comment]
@j-zimnowoda since you know how to fix this with one copy paste, how about fixing without all this work to create a bug for it? We have the 5 min rule ;)

**Comment by j-zimnowoda** [comment]
@Morriz To provide reviewers context and save their time.
