### ISSUE TITLE
After otomi upgrade the kubeclarity app does not have generated password

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#814]
**Describe the bug:** (a clear and concise description of what the bug is)

Kubeclarity works perfectly fine when deploying Otomi from scratch and enabling the app,
The issue happens only after upgrading otomi from an official release to `main` tag.

**To Reproduce**

1. Deploy otomi with version `v0.16.5`
2. In Otomi console change Otomi version and click deploy
3. Wait until deployment finishes and refresh otomi console window
4. In the apps there should be a new app called Kubeclarity
5. Enable the app and click deploy changes
6. Go to drone and observe that pipeline fails at the  `test` step with the following output
```
in helmfile.d/helmfile-50.services.yaml: failed to render values files "../values/kubeclarity/kubeclarity.gotmpl": failed to render [../values/kubeclarity/kubeclarity.gotmpl], because of template: stringTemplate:5:28: executing "stringTemplate" at <get "databasePassword">: error calling get: no value exist for key "databasePassword" in map[enabled:true logLevel:warning]
    at hfCore (/home/app/stack/dist/src/common/hf.js:44:30)
    exit code: 1
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
The password is generated when app is enabled.

**Comment by j-zimnowoda** [comment]
Looks like otomi bootstrap should be called either in during migration step or on apply step

**Comment by Morriz** [comment]
@j-zimnowoda As I said to @staticvoid255 (but he might have forgotten after acknowledging this when I explained why): the `values-schema.yaml` file needs to be copied over to `otomi-api` after any changes made, as the api uses that schema to detect secrets. We might extract it from the code base and mount it as a file at deploy time, but for tests it needs to be in there anyway, so best to follow this process.

**Comment by Morriz** [comment]
In theory the api would then write the secret as plaintext to the `env/apps/kubeclarity.yaml` file, and this should be read just fine, so something else might be happening as well

**Comment by staticvoid255** [comment]
A diff shows that all Kubeclarity related values are consistent between values-schema.yaml on the API and Core. There are however other differences that indicate that someone else failed to copy the file over previously. It would be interesting to find out when and how these files came out of sync, as there are quite significant differences without which would result in no difference between the files even with my changes. All I know is that my values are fine.

<img width="1560" alt="Screenshot 2022-06-08 at 16 29 34" src="https://user-images.githubusercontent.com/59235486/172643330-49fcd3be-ee35-45a4-b192-c35d0bd6dd01.png">
<img width="1763" alt="Screenshot 2022-06-08 at 16 36 37" src="https://user-images.githubusercontent.com/59235486/172644119-70631a53-7b95-4c46-b565-82f82119cb0f.png">
