### ISSUE TITLE
Grafana/Prometheus multitenancy

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#830]
At GU we are running 8+ different instances of Grafana corresponding to each team instance of Prometheus - with monitoring now becoming a priority we are looking to implement a SPOG 

**Describe the solution you'd like** 

Use Grafana Orgs and/or Teams to separate users from different teams

**Comment by staticvoid255** [comment]
I will implement this once Grafana 9 is added to kube-prometheus-stack

**Comment by Morriz** [comment]
You are only referring to grafana having access to platform prom source. There is more to this. 

We provide prom instances when `isMultitenant`, so teams can publish serviceMonitors which are then scraped by those instances.

RBAC is not problematic at the moment and changing it does not functionally change anything or gives us anything from architecture/networking perspective.

**Comment by Morriz** [comment]
> Note: Available in Grafana Enterprise and Grafana Cloud Advanced.
> 

Did you read this?

**Comment by Morriz** [comment]
We can always revive this once we have in-app upgrades options, but that is a long way for now. Please stick with FOSS until then.

**Comment by staticvoid255** [comment]
> Did you read this?
That wasn't there when I was researching this or I obviously would have seen it.
Grafana's [release docs for 9.0](https://grafana.com/blog/2022/06/27/new-in-grafana-9-role-based-access-control-rbac-is-now-ga/) implied it would be available for OSS users.

Regardless, I can still achieve the same result with Teams and Orgs in Grafana, which is how people did it before RBAC was introduced.

**Comment by Morriz** [comment]
> > Did you read this?
> 
> 
> 
> That wasn't there when I was researching this or I obviously would have seen it.
> 
> Grafana's [release docs for 9.0](https://grafana.com/blog/2022/06/27/new-in-grafana-9-role-based-access-control-rbac-is-now-ga/) implied it would be available for OSS users, and there has been a lot of scrutiny in the community over this.
> 

Let's be sure and maybe ask them if it is FOSS? 

> 
> Regardless, I can still achieve the same result with Teams and Orgs in Grafana, which is how people usually do it in FOSS

I believe teams and orgs are also not FOSS. We already do use their authz scripting approach, but that does not yet govern access to datasources. If we could publish datasources to be only accessible by teams with that approach we have solved the initial problem (one grafana instance vs multiple).

**Comment by staticvoid255** [comment]
closing in favour of #504

**Comment by Morriz** [comment]
@staticvoid255 can you edit that link? It is pointing to the wrong issue. (Wrong repo? You can target other org repos like this: `redkubes/otomi-console#123`)

**Comment by staticvoid255** [comment]
Whoops my bad, cheers
