### ISSUE TITLE
ServiceMonitor creation in Otomi Console

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#831]
I would like to have the option to create ServiceMonitors when I create a Service in Otomi

Something as simple as a "create ServiceMonitor" checkbox in the create service menu, with options for specifying a path for custom metrics, scrape interval etc. etc.

**Describe alternatives you've considered** 
Creating a template then getting teams to fill it in and deploy it in their own Helm charts

**Comment by Morriz** [comment]
Is this not already on the backlog? If so please remove this, or merge relevant requirements into original story.

**Comment by Morriz** [comment]
If you didn't already, then I advise to use zenhub to search for issues before creating similar ones.

**Comment by staticvoid255** [comment]
Closed as duplicate of [this ticket](https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/redkubes/unassigned-issues/8)
