### ISSUE TITLE
Apps Drag and Drop feature not workig in Mozilla Firefox browser

### ISSUE THREAD

**Issue by kingsathurthi** [redkubes/otomi-core#833]
**Apps Drag and Drop feature not working in Mozilla Firefox browser:**

**To Reproduce**

1. Go to Apps under the platform section in the side menu.
2. And Drag and Drop any of the apps from disabled apps to the Enabled apps section
3. You won't see any action if you using Mozilla Firefox browser whereas chrome browser support drag and drop of apps

**Expected behavior:** 
- Drag and drop of apps should be supported in the Mozilla Firefox browser

**Screenshots:** 

Drag and drop app operation in Mozilla Firefox browser
![Mozilla Firefox Browser drag and drop is not working](https://user-images.githubusercontent.com/24542711/176881114-5280cf88-3c5d-4db8-8ee2-0efbe22f0764.png)

Drag and drop app operation in Chrome browser
![Chrome Browser drag and drop is working](https://user-images.githubusercontent.com/24542711/176881019-058c5a5f-8252-4119-90f0-1a6d263ab3b0.png)

**Cluster(s):**

- Cloud: [DigitalOcean]
- Cluster: [otomi-on-digital-ocean]

**Versions:**

- Core Version [v0.16.9]
- K8S version: 1.22

**Desktop:** 

- OS: [Ubuntu 20.04.4 LTS (Focal Fossa)]
- Browser [Mozilla Firefox]
- Version [101.0.1 (64-bit)]
- Browser [Chrome]
- Version [103.0.5060.53 (Official Build) (64-bit)]

Note: Able to enable any disabled apps by clicking and required app and enable the tick mark

**Comment by Morriz** [comment]
Thanks! We fixed this in the console, and the fix will be included in the next otomi-core release.

**Comment by kingsathurthi** [comment]
Sounds good
