### ISSUE TITLE
An admin is not able to access its own secrets defined in the Vault app

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#837]
**Describe the bug:** (a clear and concise description of what the bug is)

An admin is not able to access its own secrets defined in Vault app 
**To Reproduce**

1. Enable Vault app and click `Deploy Changes` button. Wait until Vault app is available.
2. As an admin open Vault app
3. In the Vault app, Navigate to `secrets/team-admin/<secret name>`
4. See error on the screen suggesting that a user does not have enough permissions

**Expected behavior:** (a clear and concise description of what you expected to happen)
Admin can modify, create secrets for team admin

**Comment by diabhey** [comment]
@j-zimnowoda: What would be nice is to also have a simple behavioural chart depicting the access rights of users/admins. This was also discussed with @merll. I can elaborate it offline.

**Comment by j-zimnowoda** [comment]
We need tot ensure that admin is in `team-admin` group
