### ISSUE TITLE
Block deletion of Velero (upcoming), Vault and Gitea PV's upon PVC deletion

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#841]
I've observed that when the Gitea PVC is deleted, so too is the related volume.
In pv-azure.gotmpl we see that the default `reclaimPolicy` is `Delete` for all disk types.

For the sake of disaster prevention and recovery I think it would be preferrable to override this and set to `Retain` for Gitea and Vault too, and let the user delete them at their own wishes. My thoughts are to create a "NoDelete" policy for PV's spawned by PVC's belonging to Gitea and Vault, or any service with a label specifying that disks should not be deleted (useful in the case where the user is not using object storage as a Vault backend, for instance).

I understand that users **should** configure object storage wherever possible, but it's just not always do-able, and can be difficult to migrate from disk to object storage.

**Comment by Morriz** [comment]
This is not the right way. We never experience any data loss, so this is a non issue. By the way: clouds do the same, and the preferred way is to use a statefulset.
