### ISSUE TITLE
app requests

### ISSUE THREAD

**Issue by KiaraGrouwstra** [redkubes/otomi-core#866]
hi! i just came across otomi and feel it looks pretty nice.
thinking about services for a devops, a few others came to mind for me.

- woodpecker ci: a fork of the already included drone ci with a more permissive license
- ory hydra: SSO provider
- hashicorp terraform cloud: one of their backends for terraform state. you're probably familiar with it since Vault was already packaged. (was this omitted intentionally? licensing? circular dependency between terraform and its infra?)

i'm curious how these might fit into otomi. :)

greetings from utrecht!

**Comment by Morriz** [comment]
> hi! i just came across otomi and feel it looks pretty nice.
> 

Hi Kiara, thanks! Let me try to respond to your remarks below:

> - woodpecker ci: a fork of the already included drone ci with a more permissive license
>

Thanks for the suggestion. I never heard of it before but it sounds promising. I am not sure if our current usage of Drone is illegitimate, but I believe not. It's subscription wall is a bit annoying though.

> - ory hydra: SSO provider
> 

We had Hydra in view 2 years ago but then settled for Keycloak as Hydra was very experimental then. Keycloak is a bit heavy but has all the features one could ask for from a broker/IdP solution.

Most enterprises bring their own IdP solution and so we don't see much business value investing in another.

> - hashicorp terraform cloud: one of their backends for terraform state. you're probably familiar with it since Vault was already packaged. (was this omitted intentionally? licensing? circular dependency between terraform and its infra?)
>

Terraform is a whole different thing (infra as code abstraction) and we don't use it at all. We currently don't really care where/what/how otomi users get their k8s clusters from, as long as it fits our requirements. In the future we will probably enable our users to spin one up but how we will have to see.

> 
> 
> i'm curious how these might fit into otomi. :)
> 
> 
> 
> greetings from utrecht!
> 
> 

Greetings back from Dom city!
