### ISSUE TITLE
[API/Console] Removed configuration keeps getting re-added to values repo

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#867]
With more and more concurrent users using Otomi at the client, we are encountering the issue where configuration that has been deleted (in this case the Vault unseal config), keeps being re-introduced to the values repo while deploying other changes. This issue persists even after API and Console pods are killed.

For instance:

1. Vault unseal config is deleted in values
2. Drone pipeline runs
3. API and console pods are killed
4. User makes a change in Console (e.g. adding a secret)
5. Clicks deploy changes
6. Deleted Vault unseal config is re-introduced to values
7. Vault service is interrupted as we're not yet ready to deploy this configuration, config must be removed once again and Vault pod killed

I have asked the DevOps team to clear their browser cache, but observed the same thing happen to a user who opened Otomi in a private window, so we're stumped. It's still possible that the browser cache was at fault as I can't be sure if he opened the window before or after the API and Console pods were killed. Regardless, with more and more concurrent users it will be impossible to ensure everyone has cleared their browser cache in sync, and that a contaminated state won't make its way back to the API.
Below is a screenshot of a 3 user collision, with relevant commits highlighted:
<img width="1186" alt="Screenshot 2022-08-11 at 09 00 47" src="https://user-images.githubusercontent.com/59235486/184081421-2a18de18-8c1f-41d5-a02e-882cad0a539c.png">

**Comment by Morriz** [comment]
Hi @staticvoid255, are you aware that when you do manual commits of values that you are then responsible for restarting otomi-api? Otherwise the next person will overwrite your changes

**Comment by Morriz** [comment]
Example: I see you committed "remove vult seal config" and wonder if you restarted (and thus re-inflated the api with your changes) after that

**Comment by staticvoid255** [comment]
> Example: I see you committed "remove vault seal config" and wonder if you restarted (and thus re-inflated the api with your changes) after that

Yes, every time

**Comment by j-zimnowoda** [comment]
We will investigate it and try to reproduce locally.

**Comment by staticvoid255** [comment]
@srodenhuis this is where we initially encountered the issue and can confirm API and Console were restarted between changes

**Comment by Morriz** [comment]
This will be fixed in #925
