### ISSUE TITLE
Copy-certs job hanging without terminating

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#873]
Recently encountered cert issues with one of the teams where the fake ingress certificate was being served instead of the cert we wanted. Found out that it was due to the copy-certs job failing to terminate (after 6+ days).
Manual termination and re-triggering of the job solved the issue, but is maybe something we should look into code-wise.
To add: there were no error messages or clear reason why this was happening

**Comment by srodenhuis** [comment]
The fake ingress certificate issue was caused by wrong user configuration
