### ISSUE TITLE
Deleting otomi-welcome secret in Vault also deletes team folder

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#895]
Recently had a user point this out to me and was able to replicate:

1. Enable Vault
2. Create a team
3. Go to the Vault folder for that team
4. Delete the otomi-welcome secret
5. Team folder disappears

Workaround is currently to delete the team and recreate, but this is not ideal

**Comment by Morriz** [comment]
Is that a problem? The user should know Vault and be able to add a secret by setting the correct path that holds the team id. Just document it in otomi.io and point to Vault docs for specifics.

**Comment by Morriz** [comment]
Maybe windows users are thinking folders but what you see in Vault are mere paths. If no secret exists with the team path in it, why would it show anything? 

What I don't like is the fact that our links break when pointing to a team with no secrets, but again, we are merely facilitating usage of Vault the best we can. We don't have to spend a lot of effort on these edge cases imo. It is just how Vault works. "

If all we can do is create a dummy secret (what we do now) to make our links work and a user erases it, fine. Let them create secrets by following Vault's help docs.

**Comment by staticvoid255** [comment]
Folders/paths is just semantics, at minimum what we can do is change the name of the otomi-welcome secret to something that indicates that it shouldn't be deleted.

**Comment by j-zimnowoda** [comment]
Perhaps we could rename `Otomi-welcome` to `do-not-remove-me` or `keep-it-always`
