### ISSUE TITLE
Loki not working in multitenenant mode

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#898]
Grafana cannot connect to the Loki datasource when in multitenant mode, with the logs returning an "unauthorised" error.

<img width="1214" alt="Screenshot 2022-09-13 at 16 22 20" src="https://user-images.githubusercontent.com/59235486/190074015-ea2a6e65-863a-41af-af36-4b8869dc05c1.png">
<img width="1782" alt="Screenshot 2022-09-13 at 16 22 50" src="https://user-images.githubusercontent.com/59235486/190074018-39c0c20d-5be9-4768-af3f-dcd2fc13204f.png">

**Comment by staticvoid255** [comment]
Asking for high priority on this as we have a deadline with a client

**Comment by j-zimnowoda** [comment]
Thanks for reporting this issue I will pick this up tomorrow.

**Comment by staticvoid255** [comment]
The problem I see here is for users who are not admins, but are members of multiple teams (but not all teams), as we would then need to assign datasource permissions on a user-by-user basis which is just not do-able without generating a rainbow table of all possible team combinations. I'm going to look into this further as there may/should be a way to handle this in Grafana.

**Comment by Morriz** [comment]
This is handled by promtail. Please see how it splits up storage and sends it to Loki with the corresponding tenant id. Loki has an additional injected container that is an nginx proxy with basic auth listening to the tenant id (team name) and password.

**Comment by srodenhuis** [comment]
fixwed in v0.16.15
