### ISSUE TITLE
Critical alerts constantly firing for Kube Proxy, Scheduler and ControllerManager

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#900]
We're getting a stream of alerts of critical severity:

- KubeSchedulerDown
- KubeProxyDown
- KubeControllerManagerDown

This is a known issue with kube-prometheus-stack, where the ports and/or IP's for these services are either not accessible, or are not set in the scraping configuration

Please see [here](https://stackoverflow.com/questions/73031228/getting-kubecontrollermanager-kubeproxy-kubescheduler-down-alert-in-kube-prome) and [here ](https://github.com/prometheus-operator/kube-prometheus/issues/718)

```
Target disappeared from Prometheus target discovery.
[[FIRING:1] Notification for cluster "XXXXXX/azure/XXXXX"](https://apps.my-domain.com?receiver=critical-home)
Alert: Target disappeared from Prometheus target discovery. - critical
 Description: KubeProxy has disappeared from Prometheus target discovery.
 Graph: :chart_with_upwards_trend: Runbook: :spiral_note_pad:
 Details:
  • alertname: KubeProxyDown
  • cluster: XXXXXX/azure/XXXXX
  • prometheus: monitoring/po-prometheus
  • severity: critical
```

**Comment by srodenhuis** [comment]
You can add this to the raw_values of prometheus operator:

kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
