### ISSUE TITLE
Race condition for argocd-operator  release installation

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#965]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

Argocd sometimes fails due to unsatisfied condition during the Helm post-install hook.
```
STDERR:
  Error: release argocd-operator failed, and has been uninstalled due to atomic being set: failed post-install: timed out waiting for the condition
COMBINED OUTPUT:
  Release "argocd-operator" does not exist. Installing it now.
  Error: release argocd-operator failed, and has been uninstalled due to atomic being set: failed post-install: timed out waiting for the condition
    at hfCore (/home/app/stack/dist/src/common/hf.js:44:30)
    exit code: 1
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
The release installs successfully.

**Versions:** (seen in console's `/settings`)

- Core Version v0.16.19

**Additional context:** (add any other context about the problem here)
See CI pipeline output:
https://github.com/redkubes/otomi-core/actions/runs/3615727010/jobs/6093025870

**Comment by Morriz** [comment]
There is no output at all so what is going on? Can you not paste real logs?
