### ISSUE TITLE
Some secrets updated by a user are not stored in values repo

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#975]
**Describe the bug:** (a clear and concise description of what the bug is)

I observe app secrets edited by a user does not end up in the values repo (remote/origin) in Gitea

**To Reproduce**

1. Deploy Otomi with sops enabled
2. go to otomi console an edit prometheus (enable auth and feel password)
3. click Submit and then Deploy changes buttons
4. Observe that secret has not been changed in the Gitea repo

Note: This issue occurs if the secret file was not in repo in the first place.

**Expected behavior:** (a clear and concise description of what you expected to happen)
Updated but a user secrets are stored in Gitea repo

**Additional context:** (add any other context about the problem here)

Diving into the problem I noticed that after clicking Deploy Changes button:

Secret is stored in a .dec file in temporary user repo (e.g.: /tmp/otomi/values/bob.admin@otomi.cloud)
However, the secret is not passed to the root repo (e.g.: /tmp/otomi/values/main)
It happens because by design `.dec` files are not tracked by git

**Comment by Morriz** [comment]
Same thing like we observed yesterday, so all repos must behave similarly

**Comment by Morriz** [comment]
@j-zimnowoda I am only able to lie down today but you now know what is happening so please continue injecting envDir where it is needed. Especially prepareValues as that is only working on root repo obviously

**Comment by Morriz** [comment]
Somewhere down the line it is still not passed on and you showed me where

**Comment by j-zimnowoda** [comment]
@Morriz No worries, I am continue investigation.
So far I found out an extra condition for this issue to happen:
> the issue occurs if the secret file was not in repo in the first place.

**Comment by j-zimnowoda** [comment]
For example
in session repo I can see
`secrets.prometheus.yaml.dec` but there is no `secrets.prometheus.yaml` just after calling the `await this.repo.save(this.editor!)` function.

**Comment by j-zimnowoda** [comment]
@Morriz take a look at my draft PR: https://github.com/redkubes/otomi-core/pull/976

**Comment by j-zimnowoda** [comment]
I think that otomi-api should check if `secret.<NAME>.yaml` file exists and if not then to write file down to  `secret.<NAME>.yaml` instead of  `secret.<NAME>.yaml.dec`

**Comment by Morriz** [comment]
otomi-api should not check anything at all and just hand over the values to the core server, which has all the logic
