### ISSUE TITLE
As a user I want to install Otomi on k8s 1.24 cluster (knative upgrade)

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#980]
**Is your feature request related to a problem? Please describe.** 

According to knative release plan the knative version 1.9 will support k8s version 1.24
```
Release	Date	EOL	Min K8s Version	Notes
1.9	2023-01-24	2023-08-01	1.24	
```

**Comment by Morriz** [comment]
will be fixed by #1058
