### ISSUE TITLE
Patch deprecated github action commands 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#997]
**Is your feature request related to a problem? Please describe.** 
Our GitHub are annotated with warnings corresponding to deprecated commands(`set-output` `save-state`)  and deprecated Node 12 version 

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, docker/setup-buildx-action@v1, docker/login-action@v1, docker/build-push-action@v2
```

```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Describe the solution you'd like** 
Follow the instruction from the links above and fix the issue.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This issue should be implemented in the following repos:
- [ ] otomi-core
- [ ] otomi-api
- [ ] otomi-console
- [ ] otomi-tasks

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by staticvoid255** [comment]
PR's for internal actions are complete
Draft PR in Otomi core for the external actions, rest are coming today.

The release action needed to be migrated to a different one as the one we're using is deprecated.

**Comment by j-zimnowoda** [comment]
While making release, I found another outdated github action (see the `Create GitHub release stabe)
https://github.com/redkubes/otomi-console/actions/runs/6074521099/job/16479382719

**Comment by j-zimnowoda** [comment]
thanks
